#!/usr/bin/env python3
"""Post skill learnings to GitHub Discussions for collective intelligence.

Reads LEARNINGS.md (generated by aggregate_skill_logs.py) and posts a summary
to GitHub Discussions in the "Learnings" category of the detected repository.

Part of Issue #69 Phase 6a: Collective Intelligence Loop

Features:
- Dynamic repo detection (config override > gh repo view > skip)
- Dynamic category resolution by slug (no hardcoded IDs)
- Deduplication by date-based title pattern [Learning] YYYY-MM-DD
- Opt-out via ~/.claude/skills/discussions/config.json
- Graceful failure (warns to stderr, exits 0)
- Caches repo node ID to avoid repeated lookups
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess  # nosec B404
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Local script-directory module; co-located in plugins/abstract/scripts/.
# sys.path is set in production by the entry-point caller; for direct
# imports during testing the test files prepend the scripts dir.
from discussion_enrichment import (
    cluster_failure_modes,
    compute_trend_deltas,
    errors_by_skill_from_issues,
    format_action_items,
    format_enriched_issues,
    format_failure_modes,
    format_lens_findings,
    format_perf_summary,
    format_persistence_callout,
    format_trends,
    generate_action_items,
    parse_enriched_issues,
    parse_perf_summary,
    track_issue_persistence,
)


def get_config_dir() -> Path:
    """Get the discussions config directory."""
    return Path.home() / ".claude" / "skills" / "discussions"


def get_learnings_path() -> Path:
    """Get path to LEARNINGS.md file."""
    return Path.home() / ".claude" / "skills" / "LEARNINGS.md"


@dataclass
class DiscussionConfig:
    """Configuration for collective intelligence posting."""

    auto_post_learnings: bool = True
    target_repo: str = ""  # empty = auto-detect from gh repo view
    promotion_threshold: int = 3
    promotion_emoji: str = "\U0001f525"  # fire emoji

    @classmethod
    def load(cls) -> DiscussionConfig:
        """Load config from disk, falling back to defaults."""
        config_path = get_config_dir() / "config.json"
        if config_path.exists():
            try:
                data = json.loads(config_path.read_text())
                return cls(
                    auto_post_learnings=data.get("auto_post_learnings", True),
                    target_repo=data.get("target_repo", ""),
                    promotion_threshold=data.get("promotion_threshold", 3),
                    promotion_emoji=data.get("promotion_emoji", "\U0001f525"),
                )
            except (json.JSONDecodeError, OSError) as e:
                print(
                    f"Warning: Could not load config: {e}",
                    file=sys.stderr,
                )
        return cls()


@dataclass
class PostedRecord:
    """Tracks posted discussions to avoid duplicates."""

    # Mostly title -> discussion_url, but also stores internal keys like
    # _last_content_hash, _snapshot_history (list[dict]), and
    # _fingerprint_history (list[list[str]]).
    posted: dict[str, Any] = field(default_factory=dict)
    repo_node_id: str = ""

    @classmethod
    def load(cls) -> PostedRecord:
        """Load posted record from disk."""
        record_path = get_config_dir() / "posted.json"
        if record_path.exists():
            try:
                data = json.loads(record_path.read_text())
                return cls(
                    posted=data.get("posted", {}),
                    repo_node_id=data.get("repo_node_id", ""),
                )
            except (json.JSONDecodeError, OSError):
                pass
        return cls()

    def save(self) -> None:
        """Save posted record to disk."""
        record_path = get_config_dir() / "posted.json"
        record_path.parent.mkdir(parents=True, exist_ok=True)
        record_path.write_text(
            json.dumps(
                {"posted": self.posted, "repo_node_id": self.repo_node_id},
                indent=2,
            )
        )

    def is_posted(self, title: str) -> bool:
        """Check if a discussion with this title was already posted."""
        return title in self.posted


@dataclass
class LearningSummary:
    """Parsed summary from LEARNINGS.md."""

    last_updated: str = ""
    analysis_period: str = ""
    skills_analyzed: int = 0
    total_executions: int = 0
    high_impact_issues: list[dict[str, Any]] = field(default_factory=list)
    slow_skills: list[dict[str, Any]] = field(default_factory=list)
    low_rated_skills: list[dict[str, Any]] = field(default_factory=list)


def _extract_metadata_field(content: str, field: str) -> str:
    """Extract a bold metadata field value from content."""
    match = re.search(rf"\*\*{re.escape(field)}\*\*:\s*(.+)", content)
    return match.group(1).strip() if match else ""


def _extract_bold_field(text: str, field: str) -> str:
    """Extract a bold field value from a subsection body."""
    match = re.search(rf"\*\*{re.escape(field)}\*\*:\s*(.+)", text)
    return match.group(1).strip() if match else ""


def parse_learnings_md(content: str) -> LearningSummary:
    """Parse LEARNINGS.md into structured summary.

    Args:
        content: Raw markdown content of LEARNINGS.md

    Returns:
        LearningSummary with extracted data

    """
    summary = LearningSummary()

    # Extract metadata from header
    summary.last_updated = _extract_metadata_field(content, "Last Updated")
    summary.analysis_period = _extract_metadata_field(content, "Analysis Period")

    skills_str = _extract_metadata_field(content, "Skills Analyzed")
    summary.skills_analyzed = int(skills_str) if skills_str.isdigit() else 0

    exec_str = _extract_metadata_field(content, "Total Executions")
    summary.total_executions = int(exec_str) if exec_str.isdigit() else 0

    # Extract High-Impact Issues section
    hi_section = _extract_section(content, "## High-Impact Issues")
    if hi_section:
        summary.high_impact_issues = _parse_high_impact_issues(hi_section)

    # Extract Slow Execution section (table rows)
    slow_section = _extract_section(content, "## Slow Execution")
    if slow_section:
        for match in re.finditer(
            r"\|\s*`([^`]+)`\s*\|\s*([^\|]+)\s*\|\s*([^\|]+)\s*\|\s*(\d+)\s*\|",
            slow_section,
        ):
            summary.slow_skills.append(
                {
                    "skill": match.group(1).strip(),
                    "avg_duration": match.group(2).strip(),
                    "max_duration": match.group(3).strip(),
                    "executions": int(match.group(4).strip()),
                }
            )

    # Extract Low User Ratings section
    lr_section = _extract_section(content, "## Low User Ratings")
    if lr_section:
        for match in re.finditer(
            r"### (.+?)\s*-\s*([\d.]+)/5\.0",
            lr_section,
        ):
            summary.low_rated_skills.append(
                {
                    "skill": match.group(1).strip(),
                    "rating": float(match.group(2)),
                }
            )

    return summary


def _parse_high_impact_issues(section: str) -> list[dict[str, Any]]:
    """Parse high-impact issues from a section body."""
    issues: list[dict[str, Any]] = []
    for match in re.finditer(
        r"### (.+?)\n(.*?)(?=\n### |\n---|\n## |\Z)",
        section,
        re.DOTALL,
    ):
        skill_name = match.group(1).strip()
        body = match.group(2).strip()
        issue: dict[str, Any] = {"skill": skill_name}

        for field_name in ("Type", "Severity", "Metric"):
            value = _extract_bold_field(body, field_name)
            if value:
                issue[field_name.lower()] = value

        issues.append(issue)
    return issues


def _extract_section(content: str, heading: str) -> str | None:
    """Extract content between a heading and the next same-level heading or ---."""
    pattern = re.escape(heading) + r"\n(.*?)(?=\n## |\n---|\Z)"
    match = re.search(pattern, content, re.DOTALL)
    if match:
        return match.group(1).strip()
    return None


def format_discussion_body(summary: LearningSummary) -> str:
    """Format a Discussion post body from parsed learnings.

    Args:
        summary: Parsed learning summary

    Returns:
        Markdown-formatted discussion body

    """
    lines: list[str] = []

    lines.append("## Summary Stats")
    lines.append("")
    lines.append(f"- **Analysis Period**: {summary.analysis_period}")
    lines.append(f"- **Skills Analyzed**: {summary.skills_analyzed}")
    lines.append(f"- **Total Executions**: {summary.total_executions}")
    lines.append(f"- **Last Updated**: {summary.last_updated}")
    lines.append("")

    if summary.high_impact_issues:
        lines.append("## Top Issues")
        lines.append("")
        for issue in summary.high_impact_issues[:5]:
            severity = issue.get("severity", "unknown")
            metric = issue.get("metric", "")
            issue_type = issue.get("type", "")
            lines.append(
                f"- **{issue['skill']}** [{severity}]: {metric} ({issue_type})"
            )
        lines.append("")

    if summary.slow_skills:
        lines.append("## Slow Execution Patterns")
        lines.append("")
        for slow in summary.slow_skills[:5]:
            lines.append(
                f"- `{slow['skill']}`: avg {slow['avg_duration']}, "
                f"max {slow['max_duration']} ({slow['executions']} runs)"
            )
        lines.append("")

    if summary.low_rated_skills:
        lines.append("## Low-Rated Skills")
        lines.append("")
        for low in summary.low_rated_skills[:5]:
            lines.append(f"- `{low['skill']}`: {low['rating']}/5.0")
        lines.append("")

    lines.append("---")
    lines.append("*Auto-posted by Phase 6a Collective Intelligence Loop (Issue #69)*")
    lines.append("")
    lines.append(
        "React with \U0001f525 if you've experienced similar issues. "
        "Items with 3+ reactions will be promoted to Issues."
    )

    return "\n".join(lines)


def run_gh_graphql(query: str, variables: dict[str, Any] | None = None) -> Any:
    """Run a GraphQL query via gh api.

    Args:
        query: GraphQL query string
        variables: Optional query variables

    Returns:
        Parsed JSON response

    Raises:
        RuntimeError: If gh command fails

    """
    cmd = ["gh", "api", "graphql", "-f", f"query={query}"]
    if variables:
        for key, value in variables.items():
            cmd.extend(["-f", f"{key}={value}"])

    result = subprocess.run(  # nosec B603
        cmd,
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"gh api graphql failed (exit {result.returncode}): {result.stderr}"
        )

    return json.loads(result.stdout)


def detect_target_repo() -> tuple[str, str] | None:
    """Detect target repository (owner, name) for discussion posting.

    Priority: config override > gh repo view auto-detection.

    Returns:
        Tuple of (owner, name) or None if detection fails.

    """
    config_path = get_config_dir() / "config.json"
    if config_path.exists():
        try:
            data = json.loads(config_path.read_text())
            target = data.get("target_repo", "")
            if target and "/" in target:
                parts = target.split("/", 1)
                return (parts[0], parts[1])
        except (json.JSONDecodeError, OSError):
            pass

    # Auto-detect from current git remote
    try:
        result = subprocess.run(  # nosec B603, B607
            [
                "gh",
                "repo",
                "view",
                "--json",
                "nameWithOwner",
                "-q",
                ".nameWithOwner",
            ],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        if result.returncode == 0:
            repo_str = result.stdout.strip()
            if "/" in repo_str:
                parts = repo_str.split("/", 1)
                return (parts[0], parts[1])
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return None


def resolve_category_id(
    owner: str,
    name: str,
    slug: str,
) -> str | None:
    """Resolve a discussion category node ID by slug.

    Args:
        owner: Repository owner.
        name: Repository name.
        slug: Category slug (e.g., "learnings").

    Returns:
        Category node ID or None if not found.

    """
    query = """
    query($owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) {
        discussionCategories(first: 25) {
          nodes { id slug }
        }
      }
    }
    """

    try:
        response = run_gh_graphql(
            query,
            variables={"owner": owner, "repo": name},
        )
        categories = response["data"]["repository"]["discussionCategories"]["nodes"]
        for cat in categories:
            if cat["slug"] == slug:
                return str(cat["id"])
    except (RuntimeError, KeyError, json.JSONDecodeError):
        pass

    return None


def get_repo_node_id(
    record: PostedRecord,
    owner: str,
    name: str,
) -> str:
    """Get the repository node ID, using cache if available.

    Args:
        record: PostedRecord to cache the ID in.
        owner: Repository owner.
        name: Repository name.

    Returns:
        Repository node ID string.

    """
    if record.repo_node_id:
        return record.repo_node_id

    query = """
    query($owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) { id }
    }
    """

    response = run_gh_graphql(
        query,
        variables={"owner": owner, "repo": name},
    )
    node_id = response["data"]["repository"]["id"]
    record.repo_node_id = node_id
    record.save()
    return str(node_id)


def check_existing_discussion(
    title: str,
    owner: str,
    name: str,
) -> str | None:
    """Check if a discussion with this title already exists.

    Args:
        title: Discussion title to search for.
        owner: Repository owner.
        name: Repository name.

    Returns:
        Discussion URL if found, None otherwise.

    """
    target_repo = f"{owner}/{name}"
    escaped_title = title.replace('"', '\\"')
    query = (
        f'query {{ search(query: "repo:{target_repo}'
        f' in:title \\"{escaped_title}\\"", '
        "type: DISCUSSION, first: 5) { nodes { ... on Discussion "
        "{ title url } } } }"
    )

    try:
        response = run_gh_graphql(query)
        nodes = response.get("data", {}).get("search", {}).get("nodes", [])
        for node in nodes:
            if node.get("title") == title:
                return str(node.get("url", ""))
    except (RuntimeError, KeyError, json.JSONDecodeError):
        pass

    return None


def create_discussion(
    repo_id: str,
    category_id: str,
    title: str,
    body: str,
) -> str:
    """Create a GitHub Discussion.

    Args:
        repo_id: Repository node ID
        category_id: Discussion category node ID
        title: Discussion title
        body: Discussion body (markdown)

    Returns:
        URL of the created discussion

    """
    query = """
    mutation($repoId: ID!, $categoryId: ID!, $title: String!, $body: String!) {
      createDiscussion(input: {
        repositoryId: $repoId,
        categoryId: $categoryId,
        title: $title,
        body: $body
      }) {
        discussion {
          url
        }
      }
    }
    """

    response = run_gh_graphql(
        query,
        variables={
            "repoId": repo_id,
            "categoryId": category_id,
            "title": title,
            "body": body,
        },
    )

    return str(response["data"]["createDiscussion"]["discussion"]["url"])


def _load_and_validate_learnings(
    path: Path,
) -> tuple[LearningSummary, str] | None:
    """Load LEARNINGS.md, validate it has content worth posting.

    Returns (summary, raw_content) so the enrichment composer can
    parse fields the legacy LearningSummary does not retain.
    """
    if not path.exists():
        print(
            f"Warning: {path} not found. Run aggregate-logs first.",
            file=sys.stderr,
        )
        return None

    content = path.read_text()
    if not content.strip():
        print("Warning: LEARNINGS.md is empty.", file=sys.stderr)
        return None

    summary = parse_learnings_md(content)
    if summary.skills_analyzed == 0 and summary.total_executions == 0:
        print("No learnings to post (empty analysis).", file=sys.stderr)
        return None

    return (summary, content)


def compose_enriched_body(
    summary: LearningSummary,
    content: str,
    record: PostedRecord,
) -> str:
    """Build the full discussion body with enrichment sections.

    Layers (in order):
    1. Original summary (legacy format_discussion_body output)
    2. Enriched issues with Detail + Recent Errors
    3. Performance summary table
    4. Named failure modes (clustered errors)
    5. Insights & Recommendations (lens-driven)
    6. Trends vs previous snapshot
    7. Persistent issues callout
    8. Action items
    """
    enriched_issues = parse_enriched_issues(content)
    perf_rows = parse_perf_summary(content)
    failure_modes = cluster_failure_modes(errors_by_skill_from_issues(enriched_issues))

    # Lens findings: skip if metrics_by_skill not available; we don't
    # rebuild the SkillLogSummary objects from LEARNINGS.md alone.
    findings: list = []

    # Trend deltas: compare against last snapshot stored in PostedRecord.
    snapshot_history = record.posted.get("_snapshot_history", [])
    last_snapshot = snapshot_history[-1] if snapshot_history else None
    current_snapshot = {
        row["skill"]: {
            "success_rate": _safe_pct(row.get("success_rate", "0%")),
            "total_executions": _safe_int(row.get("executions", "0")),
        }
        for row in perf_rows
    }
    deltas = compute_trend_deltas(current_snapshot, last_snapshot)

    # Persistence: compare current issue fingerprints against history.
    fingerprint_history = record.posted.get("_fingerprint_history", [])
    persistent = track_issue_persistence(
        enriched_issues, fingerprint_history, threshold=3
    )

    items = generate_action_items(findings, persistent)

    sections = [
        _legacy_summary_block(summary),
        format_enriched_issues(enriched_issues),
        format_perf_summary(perf_rows),
        format_failure_modes(failure_modes),
        format_lens_findings(findings),
        format_trends(deltas),
        format_persistence_callout(persistent),
        format_action_items(items),
        _footer_block(),
    ]
    return "\n\n".join(s for s in sections if s).rstrip() + "\n"


def _legacy_summary_block(summary: LearningSummary) -> str:
    """Original Summary Stats block, kept for continuity at top of post."""
    lines = ["## Summary Stats", ""]
    lines.append(f"- **Analysis Period**: {summary.analysis_period}")
    lines.append(f"- **Skills Analyzed**: {summary.skills_analyzed}")
    lines.append(f"- **Total Executions**: {summary.total_executions}")
    lines.append(f"- **Last Updated**: {summary.last_updated}")
    return "\n".join(lines)


def _footer_block() -> str:
    return (
        "---\n"
        "*Auto-posted by Phase 6a Collective Intelligence Loop "
        "(Issue #69)*\n\n"
        "React with \U0001f525 if you've experienced similar issues. "
        "Items with 3+ reactions will be promoted to Issues."
    )


def _safe_pct(value: str) -> float:
    """Parse '40.0%' -> 40.0; tolerate outer whitespace and missing %."""
    try:
        # Strip whitespace FIRST so the % is at the end for rstrip.
        # Previously `.rstrip("%").strip()` silently returned 0.0 on
        # "  40.0%  " because % was not the trailing character.
        return float(value.strip().rstrip("%"))
    except (ValueError, AttributeError):
        return 0.0


def _safe_int(value: str) -> int:
    try:
        return int(str(value).strip())
    except (ValueError, AttributeError):
        return 0


def _record_post_artifacts(
    record: PostedRecord,
    enriched_issues: list,
    perf_rows: list[dict[str, str]],
) -> None:
    """Append snapshot + fingerprints to PostedRecord for next post.

    Capped at the last 5 entries to bound posted.json growth.
    """
    snapshot = {
        row["skill"]: {
            "success_rate": _safe_pct(row.get("success_rate", "0%")),
            "total_executions": _safe_int(row.get("executions", "0")),
        }
        for row in perf_rows
    }
    fingerprints = [f"{issue.skill}|{issue.issue_type}" for issue in enriched_issues]

    history = record.posted.get("_snapshot_history", [])
    history.append(snapshot)
    record.posted["_snapshot_history"] = history[-5:]

    fp_history = record.posted.get("_fingerprint_history", [])
    fp_history.append(fingerprints)
    record.posted["_fingerprint_history"] = fp_history[-5:]


def post_learnings(learnings_path: Path | None = None) -> str | None:
    """Main entry point: parse LEARNINGS.md and post to Discussions.

    Args:
        learnings_path: Override path to LEARNINGS.md (for testing)

    Returns:
        Discussion URL if posted, None if skipped

    """
    result = _resolve_and_post(learnings_path)
    return result


def _resolve_and_post(learnings_path: Path | None) -> str | None:
    """Resolve config, validate inputs, and post to Discussions."""
    config = DiscussionConfig.load()
    if not config.auto_post_learnings:
        print("Learnings posting disabled via config.", file=sys.stderr)
        return None

    repo = detect_target_repo()
    if repo is None:
        print(
            "Could not detect target repository. Skipping.",
            file=sys.stderr,
        )
        return None
    owner, name = repo

    category_id = resolve_category_id(owner, name, "learnings")
    if category_id is None:
        print(
            f'No "learnings" discussion category on {owner}/{name}. Skipping.',
            file=sys.stderr,
        )
        return None

    path = learnings_path or get_learnings_path()
    loaded = _load_and_validate_learnings(path)
    if loaded is None:
        return None
    summary, content = loaded

    return _post_if_new(summary, content, owner, name, category_id)


def _post_if_new(
    summary: LearningSummary,
    content: str,
    owner: str,
    name: str,
    category_id: str,
) -> str | None:
    """Post a discussion if not already posted today AND content is new."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"[Learning] {today}"

    record = PostedRecord.load()
    if record.is_posted(title):
        print(
            f"Already posted for today ({title}). Skipping.",
            file=sys.stderr,
        )
        cached = record.posted[title]
        return cached if isinstance(cached, str) else None

    existing_url = check_existing_discussion(title, owner, name)
    if existing_url:
        print(
            f"Discussion already exists: {existing_url}. Skipping.",
            file=sys.stderr,
        )
        record.posted[title] = existing_url
        record.save()
        return existing_url

    # Build enriched body using snapshot/fingerprint history from record.
    body = compose_enriched_body(summary, content, record)
    content_hash = hashlib.sha256(body.encode()).hexdigest()[:12]

    if record.posted.get("_last_content_hash") == content_hash:
        print(
            "Content identical to last post. Skipping.",
            file=sys.stderr,
        )
        return None

    repo_id = get_repo_node_id(record, owner, name)
    url = create_discussion(repo_id, category_id, title, body)

    record.posted[title] = url
    record.posted["_last_content_hash"] = content_hash
    _record_post_artifacts(
        record,
        parse_enriched_issues(content),
        parse_perf_summary(content),
    )
    record.save()

    print(f"Posted enriched learning summary: {url}")
    return url


def main() -> None:
    """CLI entry point."""
    try:
        url = post_learnings()
        if url:
            print(f"\nDiscussion URL: {url}")
    except RuntimeError as e:
        print(f"Warning: Could not post learnings: {e}", file=sys.stderr)
        sys.exit(0)  # Graceful failure
    except FileNotFoundError:
        print(
            "Warning: gh CLI not found. Install GitHub CLI to enable "
            "collective intelligence features.",
            file=sys.stderr,
        )
        sys.exit(0)


if __name__ == "__main__":
    main()
