#!/usr/bin/env python3
"""Post insight findings to GitHub Discussions.

Posts findings from the insight engine to the "Insights"
(or "Learnings") discussion category. Each finding gets
a typed title prefix and structured body.

Uses InsightRegistry for content-hash dedup so the same
finding is never posted twice within 30 days.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone

from insight_registry import InsightRegistry
from insight_types import Finding
from post_learnings_to_discussions import (
    PostedRecord,
    create_discussion,
    detect_target_repo,
    get_repo_node_id,
    resolve_category_id,
)


def format_insight_title(finding: Finding) -> str:
    """Generate a discussion title from a finding.

    Args:
        finding: The finding to title.

    Returns:
        Title string with type prefix.

    """
    return finding.title()


def format_insight_body(finding: Finding) -> str:
    """Format a Discussion post body from a finding.

    Args:
        finding: The finding to format.

    Returns:
        Markdown-formatted discussion body.

    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = []

    lines.append("## Finding")
    lines.append("")
    lines.append(finding.summary)
    lines.append("")
    lines.append(f"**Severity:** {finding.severity}")
    if finding.skill:
        lines.append(f"**Skill:** `{finding.skill}`")
    lines.append(f"**Source:** {finding.source}")
    lines.append(f"**Generated:** {today}")
    lines.append("")

    lines.append("## Evidence")
    lines.append("")
    lines.append(finding.evidence)
    lines.append("")

    lines.append("## Recommended Action")
    lines.append("")
    lines.append(finding.recommendation)
    lines.append("")

    if finding.related_files:
        lines.append("## Related Files")
        lines.append("")
        for f in finding.related_files:
            lines.append(f"- `{f}`")
        lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by Insight Engine (Phase 6a+)*")
    lines.append(
        "React with \U0001f525 to prioritize. 3+ reactions will promote to Issue."
    )

    return "\n".join(lines)


def post_findings(
    findings: list[Finding],
    registry: InsightRegistry | None = None,
    category_slug: str = "insights",
) -> list[str]:
    """Post a list of findings to GitHub Discussions.

    Deduplicates via InsightRegistry before posting.
    Falls back to "learnings" category if "insights"
    doesn't exist.

    Args:
        findings: List of findings to post.
        registry: InsightRegistry for dedup (created if None).
        category_slug: Discussion category slug.

    Returns:
        List of posted discussion URLs.

    """
    if not findings:
        return []

    repo = detect_target_repo()
    if repo is None:
        print(
            "Could not detect target repository. Skipping.",
            file=sys.stderr,
        )
        return []
    owner, name = repo

    # Try "insights" category, fall back to "learnings"
    category_id = resolve_category_id(owner, name, category_slug)
    if category_id is None and category_slug == "insights":
        category_id = resolve_category_id(owner, name, "learnings")
    if category_id is None:
        print(
            f'No "{category_slug}" or "learnings" discussion '
            f"category on {owner}/{name}. Skipping.",
            file=sys.stderr,
        )
        return []

    if registry is None:
        registry = InsightRegistry()

    record = PostedRecord.load()
    repo_id = get_repo_node_id(record, owner, name)

    posted_urls: list[str] = []

    for finding in findings:
        # Check local dedup
        action = registry.check_local(finding)
        if action == "skip":
            continue

        title = format_insight_title(finding)
        body = format_insight_body(finding)

        try:
            url = create_discussion(repo_id, category_id, title, body)
            registry.record_posted(finding, url)
            posted_urls.append(url)
            print(f"Posted insight: {url}")
        except RuntimeError as e:
            print(
                f"Warning: Could not post insight: {e}",
                file=sys.stderr,
            )

    return posted_urls


def main() -> None:
    """CLI entry point for manual posting."""
    print("Use insight_analyzer.py to generate findings first.")
    print("This script is called by the Stop hook pipeline.")


if __name__ == "__main__":
    main()
