# Feature Review Configuration for Claude Night Market
# Plugin marketplace for Claude Code - optimized for LLM tooling development
#
# This configuration reflects the unique needs of an LLM plugin ecosystem:
# - Token efficiency is critical (users pay per token)
# - API stability matters (plugins depend on each other)
# - Integration is paramount (plugins must compose well)
# - Readability enables contribution (open source project)

version: 1

# ─────────────────────────────────────────────────────────────────
# SCORING WEIGHTS
# Tuned for plugin ecosystem priorities
# ─────────────────────────────────────────────────────────────────

weights:
  value:
    reach: 0.20              # Fewer users than consumer apps
    impact: 0.35             # Developer experience is critical
    business_value: 0.20     # OSS - community value over revenue
    time_criticality: 0.25   # Fast iteration matters in AI space
  cost:
    effort: 0.35             # Balance effort vs other factors
    risk: 0.35               # Plugin stability is important
    complexity: 0.30         # Complexity affects maintainability

# ─────────────────────────────────────────────────────────────────
# SCORE THRESHOLDS
# Slightly higher bar - quality over quantity for plugins
# ─────────────────────────────────────────────────────────────────

thresholds:
  high_priority: 2.8         # Higher bar for "must do now"
  medium_priority: 1.8       # Reasonable roadmap threshold
  confidence_warning: 0.6    # Require decent confidence

# ─────────────────────────────────────────────────────────────────
# CLASSIFICATION PATTERNS
# Plugin-specific feature detection
# ─────────────────────────────────────────────────────────────────

classification:
  default_type: reactive     # Most plugin features are user-invoked
  default_data: static       # Skills/commands are versioned artifacts

  patterns:
    proactive_patterns:
      - "*auto*"
      - "*suggest*"
      - "*hook*"             # Hooks are proactive by nature
      - "*watch*"
      - "*monitor*"
      - "*background*"
      - "*prefetch*"
      - "*cache-warm*"

    dynamic_patterns:
      - "*session*"
      - "*context*"          # Context window state
      - "*memory*"           # Memory palace features
      - "*realtime*"
      - "*stream*"
      - "*live*"

# ─────────────────────────────────────────────────────────────────
# TRADEOFF DIMENSION WEIGHTS
# Optimized for LLM plugin development
# ─────────────────────────────────────────────────────────────────

tradeoffs:
  quality: 1.0               # Results must be correct
  latency: 0.9               # Important but not always critical
  token_usage: 1.4           # CRITICAL - users pay per token
  resource_usage: 0.7        # Less critical for CLI tools
  redundancy: 0.6            # Plugins can fail gracefully
  readability: 1.2           # OSS needs readable code
  scalability: 0.6           # Single-user CLI, not web scale
  integration: 1.3           # Plugins MUST compose well
  api_surface: 1.3           # Breaking changes hurt ecosystem

# ─────────────────────────────────────────────────────────────────
# GITHUB INTEGRATION
# Configured for claude-night-market repository
# ─────────────────────────────────────────────────────────────────

github:
  enabled: true
  auto_label: true
  label_prefix: "priority/"

  default_labels:
    - enhancement
    - feature-review

  priority_labels:
    high: "priority/high"
    medium: "priority/medium"
    low: "priority/low"

  classification_labels:
    proactive: "type/proactive"
    reactive: "type/reactive"
    static: "data/static"
    dynamic: "data/dynamic"

  # Custom labels for plugin ecosystem
  custom_labels:
    skill: "component/skill"
    command: "component/command"
    agent: "component/agent"
    hook: "component/hook"
    cross_plugin: "scope/cross-plugin"

  issue_template: |
    ## Feature Request

    **Generated by:** `/feature-review`
    **Plugin:** {{ plugin_name }}
    **Priority Score:** {{ score }} ({{ priority }})
    **Classification:** {{ type }}/{{ data }}
    **Kano Category:** {{ kano }}

    ---

    ### Description
    {{ description }}

    ### Value Proposition

    | Factor | Score | Rationale |
    |--------|-------|-----------|
    | Reach | {{ reach }}/13 | {{ reach_rationale }} |
    | Impact | {{ impact }}/13 | {{ impact_rationale }} |
    | Business Value | {{ business_value }}/13 | {{ bv_rationale }} |
    | Time Criticality | {{ time_criticality }}/13 | {{ tc_rationale }} |

    ### Cost Assessment

    | Factor | Score | Rationale |
    |--------|-------|-----------|
    | Effort | {{ effort }}/13 | {{ effort_rationale }} |
    | Risk | {{ risk }}/13 | {{ risk_rationale }} |
    | Complexity | {{ complexity }}/13 | {{ complexity_rationale }} |

    ### Tradeoff Considerations

    **Token Efficiency:** {{ token_assessment }}
    **Integration Impact:** {{ integration_assessment }}
    **API Surface Changes:** {{ api_assessment }}

    {{ tradeoffs_summary }}

    ### Acceptance Criteria

    {{ acceptance_criteria }}

    ### Related Features

    {{ related_features }}

    ---

    <details>
    <summary>Scoring Breakdown</summary>

    ```
    Value Score: {{ value_score }}
    Cost Score: {{ cost_score }}
    Confidence: {{ confidence }}
    Final Score: {{ score }}
    ```

    </details>

    *Created via `/feature-review --create-issues`*

# ─────────────────────────────────────────────────────────────────
# INVENTORY SETTINGS
# Plugin-specific feature discovery
# ─────────────────────────────────────────────────────────────────

inventory:
  # Scan all plugin directories
  scan_paths:
    - "plugins/*/commands/"
    - "plugins/*/skills/"
    - "plugins/*/agents/"
    - "plugins/*/hooks/"
    - "plugins/*/.claude-plugin/"

  exclude_patterns:
    - "**/.worktrees/**"
    - "**/test*"
    - "**/mock*"
    - "**/__pycache__/**"
    - "**/node_modules/**"
    - "**/.git/**"
    - "**/archive/**"

  # Plugin-specific feature markers
  feature_markers:
    - "---\nname:"           # YAML frontmatter (skills, commands)
    - "\"name\":"            # JSON (plugin.json)
    - "# @feature"           # Comment marker
    - "def "                 # Python functions
    - "class "               # Class definitions

  # Group features by plugin
  group_by_plugin: true

# ─────────────────────────────────────────────────────────────────
# OUTPUT SETTINGS
# ─────────────────────────────────────────────────────────────────

output:
  format: markdown
  include_rationale: true
  include_tradeoffs: true
  max_suggestions: 15        # More suggestions for larger project

  sections:
    - inventory
    - classification
    - scoring
    - tradeoffs
    - cross_plugin_analysis  # Special section for plugin interactions
    - suggestions
    - github_actions

  # Plugin-specific output
  group_by_plugin: true
  show_plugin_health: true   # Overall health score per plugin

# ─────────────────────────────────────────────────────────────────
# BACKLOG SETTINGS
# ─────────────────────────────────────────────────────────────────

backlog:
  max_items: 25
  stale_days: 45             # Longer for OSS project
  auto_archive: false

  file: "docs/backlog/feature-queue.md"

  # Categories specific to plugin development
  categories:
    - new_skill
    - new_command
    - new_agent
    - skill_improvement
    - cross_plugin
    - documentation
    - performance
    - developer_experience

# ─────────────────────────────────────────────────────────────────
# PLUGIN-SPECIFIC SETTINGS
# Custom settings for claude-night-market
# ─────────────────────────────────────────────────────────────────

plugins:
  # Plugin categories for grouping
  categories:
    core:
      - abstract            # Plugin development tools
      - conservation        # Context optimization
      - imbue              # Workflow methodologies
    workflow:
      - sanctum            # Git/GitHub workflows
      - spec-kit           # Specification management
      - pensive            # Code review
    specialized:
      - parseltongue       # Python expertise
      - conjure            # Model delegation
      - memory-palace      # Knowledge management
    utility:
      - leyline            # Plugin management
      - archetypes         # Prompt patterns

  # Cross-plugin dependency tracking
  track_dependencies: true

  # Alert when features might conflict
  conflict_detection: true

# ─────────────────────────────────────────────────────────────────
# KANO CATEGORY HINTS
# Help classify features for this ecosystem
# ─────────────────────────────────────────────────────────────────

kano_hints:
  basic:
    # Features users expect - absence causes dissatisfaction
    - "error handling"
    - "help text"
    - "basic documentation"
    - "conventional commit support"
    - "git integration"

  performance:
    # More is better - competitive differentiators
    - "token optimization"
    - "context efficiency"
    - "parallel execution"
    - "caching"
    - "incremental processing"

  delighters:
    # Unexpected features that create joy
    - "AI-powered suggestions"
    - "automatic learning"
    - "cross-plugin orchestration"
    - "visual feedback"
    - "smart defaults"
