# Category: Decisions (Announcement format)
# Requires manual category creation: Settings → Discussions → New Category
#   Name: Decisions | Format: Announcement | Description: War room outcomes and ADR-style decision records
title: "[Decision] "
labels:
  - "decision"
body:
  - type: markdown
    attributes:
      value: |
        ## Decision Record
        Document a deliberated decision for cross-session reference.
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current status of this decision
      options:
        - Accepted
        - Superseded
        - Deprecated
        - Under Review
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What situation or problem prompted this decision?
      placeholder: Describe the background, constraints, and forces at play.
    validations:
      required: true
  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: What was decided?
      placeholder: We will use / adopt / implement...
    validations:
      required: true
  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      description: What are the positive, negative, and neutral consequences of this decision?
      placeholder: |
        Positive: ...
        Negative: ...
        Neutral: ...
    validations:
      required: true
  - type: input
    id: reversibility-score
    attributes:
      label: Reversibility Score
      description: "War room RS score (0.00 - 1.00). Higher = less reversible."
      placeholder: "0.65"
  - type: input
    id: related
    attributes:
      label: Related PRs/Issues
      description: "Link related PRs, issues, or prior decisions (e.g., #42, #103)"
      placeholder: "#42, #103"
