"""Tests for post_review_insights.

Feature: Convert review markdown into Findings and post to Discussions
    As a maintainer running /pr-review
    I want my review's findings auto-posted to GitHub Discussions
    So that recent iterative capabilities feed the collective memory
"""

from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "scripts"))

from post_review_insights import (  # noqa: E402 - sys.path adjusted above to discover scripts dir
    extract_blockers,
    extract_non_blocking,
    extract_verdict,
    main,
    parse_review_markdown,
    review_to_findings,
)

# ---------------------------------------------------------------------------
# Sample review markdown (subset of the real /pr-review output format)
# ---------------------------------------------------------------------------

SAMPLE_REVIEW = """\
# PR Review: #417 - perf(imbue): bounded-reads parallel safety

**Verdict:** Request changes
**Blocking:** 3 | **Non-blocking:** 2 | **ADR violations:** 0

## Blocking findings

### B1 - AI-attribution regex false-positives on bare URL/domain matches

`plugins/imbue/hooks/vow_no_ai_attribution.py:31-32`

The bare `claude.ai` and `anthropic.com` patterns false-positive on
legitimate URL mentions in commit messages.

Suggested direction: scope the URL patterns to attribution contexts.

### B2 - 50-thread atomicity test passes without flock due to GIL

`plugins/imbue/tests/unit/hooks/test_vow_bounded_reads.py:631-672`

CPython's GIL serializes the JSON parse-modify-write inside
`_atomic_increment` at the bytecode level.

Suggested direction: inject a deterministic race.

## Non-blocking findings

| ID | Source | Where | Concern |
|----|--------|-------|---------|
| NB1 | Security | `vow_bounded_reads.py:119` | flock failure swallowed silently |
| NB2 | Security | `validators/markdown_wrap.py:160` | open(path) on caller paths |

---

*Review generated by 4-agent parallel dispatch.*
"""


class TestExtractVerdict:
    """Feature: Pull the verdict line from review markdown."""

    @pytest.mark.unit
    def test_extracts_verdict_line(self) -> None:
        """Scenario: '**Verdict:** Request changes' is recognized."""
        assert extract_verdict(SAMPLE_REVIEW) == "Request changes"

    @pytest.mark.unit
    def test_missing_verdict_returns_unknown(self) -> None:
        """Scenario: No verdict line"""
        assert extract_verdict("# nope\n") == "unknown"


class TestExtractBlockers:
    """Feature: Parse Blocking findings into structured records."""

    @pytest.mark.unit
    def test_finds_two_blockers(self) -> None:
        blockers = extract_blockers(SAMPLE_REVIEW)
        assert len(blockers) == 2
        assert blockers[0]["id"] == "B1"
        assert "AI-attribution regex" in blockers[0]["title"]
        assert "vow_no_ai_attribution.py:31-32" in blockers[0]["body"]

    @pytest.mark.unit
    def test_empty_review_returns_empty(self) -> None:
        assert extract_blockers("# nothing\n") == []


class TestExtractNonBlocking:
    """Feature: Parse the Non-blocking table into rows."""

    @pytest.mark.unit
    def test_finds_table_rows(self) -> None:
        rows = extract_non_blocking(SAMPLE_REVIEW)
        assert len(rows) == 2
        assert rows[0]["id"] == "NB1"
        assert "vow_bounded_reads.py:119" in rows[0]["where"]

    @pytest.mark.unit
    def test_no_table_returns_empty(self) -> None:
        assert extract_non_blocking("no table here\n") == []


class TestParseReviewMarkdown:
    """Feature: Combined parser produces a structured ReviewSummary."""

    @pytest.mark.unit
    def test_returns_complete_summary(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        assert summary.verdict == "Request changes"
        assert len(summary.blockers) == 2
        assert len(summary.non_blocking) == 2


class TestReviewToFindings:
    """Feature: ReviewSummary -> list[Finding] for post_findings()."""

    @pytest.mark.unit
    def test_each_blocker_becomes_a_finding(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        findings = review_to_findings(summary, pr_number=417)
        # Two blockers + two non-blocking = 4 findings.
        assert len(findings) == 4
        first = findings[0]
        assert first.type == "PR Finding"
        assert first.severity == "high"  # blockers are high
        assert "B1" in first.summary

    @pytest.mark.unit
    def test_finding_includes_pr_link_in_evidence(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        findings = review_to_findings(summary, pr_number=417)
        assert any("#417" in f.evidence for f in findings)

    @pytest.mark.unit
    def test_non_blocking_marked_medium(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        findings = review_to_findings(summary, pr_number=417)
        nb = [f for f in findings if f.summary.startswith("NB")]
        assert nb
        assert all(f.severity == "medium" for f in nb)


class TestMain:
    """Feature: CLI entry point reads file, posts findings."""

    @pytest.mark.unit
    def test_main_skips_when_no_findings(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        empty = tmp_path / "empty.md"
        empty.write_text("# nothing\n")
        monkeypatch.setattr(sys, "argv", ["post_review_insights.py", str(empty)])
        with pytest.raises(SystemExit) as exc:
            main()
        assert exc.value.code == 0

    @pytest.mark.unit
    def test_main_calls_post_findings_when_findings_found(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        review = tmp_path / "pr-417-review.md"
        review.write_text(SAMPLE_REVIEW)
        monkeypatch.setattr(sys, "argv", ["post_review_insights.py", str(review)])

        with patch("post_review_insights.post_findings") as mock_post:
            mock_post.return_value = ["https://example.com/d/1"]
            with pytest.raises(SystemExit) as exc:
                main()
            assert exc.value.code == 0
            mock_post.assert_called_once()
            posted_findings = mock_post.call_args[0][0]
            assert len(posted_findings) == 4  # 2 blockers + 2 non-blocking

    @pytest.mark.unit
    def test_main_missing_file_exits_nonzero(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(sys, "argv", ["post_review_insights.py", "/nonexistent.md"])
        with pytest.raises(SystemExit) as exc:
            main()
        assert exc.value.code != 0


# ---------------------------------------------------------------------------
# Invariant-encoding tests (Phase 2.5 per test-updates skill)
# ---------------------------------------------------------------------------


class TestSeverityContractInvariant:
    """Invariant: severity mapping is a design decision.

    Blockers MUST map to "high" severity so they rank first in
    discussion lists and trigger any severity-gated downstream
    automation. Non-blocking rows MUST map to "medium" — never "low"
    (too easily ignored) and never "high" (false urgency).

    If this test breaks, someone is changing the severity contract.
    Present the 3 options before updating the assertion:
    1. Preserve: revert the change, blockers stay high
    2. Layer: add a severity override parameter, keep default
    3. Revise: document the new severity strategy in an ADR
    """

    @pytest.mark.unit
    def test_every_blocker_becomes_high(self) -> None:
        """All blockers, regardless of count or content, get severity=high."""
        from post_review_insights import (
            Finding,  # noqa: PLC0415 - local import to colocate with test
        )

        markdown = (
            "**Verdict:** Request changes\n\n"
            "## Blocking findings\n\n"
            "### B1 - one\n\nbody 1\n\n"
            "### B2 - two\n\nbody 2\n\n"
            "### B3 - three\n\nbody 3\n"
        )
        summary = parse_review_markdown(markdown)
        findings: list[Finding] = review_to_findings(summary, pr_number=1)
        blockers = [f for f in findings if f.summary.startswith("B")]
        assert len(blockers) == 3
        assert all(f.severity == "high" for f in blockers), (
            "INVARIANT VIOLATION: not all blockers are severity=high. "
            "See test docstring for the 3-option decision before changing."
        )

    @pytest.mark.unit
    def test_every_non_blocking_becomes_medium(self) -> None:
        """All non-blocking rows get severity=medium — never low or high."""
        markdown = (
            "**Verdict:** Approve\n\n"
            "## Non-blocking findings\n\n"
            "| ID | Source | Where | Concern |\n"
            "|----|--------|-------|---------|\n"
            "| NB1 | docs | a.py:1 | typo |\n"
            "| NB2 | perf | b.py:2 | slow |\n"
        )
        summary = parse_review_markdown(markdown)
        findings = review_to_findings(summary, pr_number=1)
        non_blockers = [f for f in findings if f.summary.startswith("NB")]
        assert len(non_blockers) == 2
        assert all(f.severity == "medium" for f in non_blockers), (
            "INVARIANT VIOLATION: non-blocking must be medium. "
            "low rank would hide them; high rank would inflate urgency."
        )


class TestExtractPrNumber:
    """Feature: Extract PR number from the standard review heading."""

    @pytest.mark.unit
    def test_extracts_from_standard_heading(self) -> None:
        """Scenario: '# PR Review: #417 - title' -> 417"""
        from post_review_insights import extract_pr_number

        assert extract_pr_number("# PR Review: #417 - some title\n") == 417

    @pytest.mark.unit
    def test_missing_heading_returns_none(self) -> None:
        """Scenario: no heading at all"""
        from post_review_insights import extract_pr_number

        assert extract_pr_number("no pr heading here\n") is None

    @pytest.mark.unit
    def test_different_heading_format_returns_none(self) -> None:
        """Scenario: '# Review of PR 417' (non-standard) -> None.

        The parser is deliberately strict about the heading format
        because downstream Findings embed this PR number in their
        evidence. A false match (e.g., pulling '417' from arbitrary
        prose) would corrupt the evidence link.
        """
        from post_review_insights import extract_pr_number

        assert extract_pr_number("# Review of PR 417\n") is None


class TestReviewWithOnlyOneKind:
    """Edge case: reviews in the wild aren't always balanced."""

    @pytest.mark.unit
    def test_review_with_only_blockers_no_table(self) -> None:
        """Approved-with-caveats pattern: blockers but nothing to note."""
        markdown = (
            "**Verdict:** Request changes\n\n"
            "## Blocking findings\n\n"
            "### B1 - x\n\nbody\n\n"
        )
        summary = parse_review_markdown(markdown)
        findings = review_to_findings(summary, pr_number=1)
        assert len(findings) == 1
        assert findings[0].severity == "high"

    @pytest.mark.unit
    def test_review_with_only_non_blocking(self) -> None:
        """Clean-approve-with-suggestions pattern: no blockers, NB table only."""
        markdown = (
            "**Verdict:** Approve\n\n"
            "## Non-blocking findings\n\n"
            "| ID | Source | Where | Concern |\n"
            "|----|--------|-------|---------|\n"
            "| NB1 | docs | a.py:1 | typo |\n"
        )
        summary = parse_review_markdown(markdown)
        findings = review_to_findings(summary, pr_number=1)
        assert len(findings) == 1
        assert findings[0].severity == "medium"
