"""Tests for post_review_insights.

Feature: Convert review markdown into Findings and post to Discussions
    As a maintainer running /pr-review
    I want my review's findings auto-posted to GitHub Discussions
    So that recent iterative capabilities feed the collective memory
"""

from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "scripts"))

from post_review_insights import (  # noqa: E402 - sys.path adjusted above to discover scripts dir
    extract_blockers,
    extract_non_blocking,
    extract_verdict,
    main,
    parse_review_markdown,
    review_to_findings,
)

# ---------------------------------------------------------------------------
# Sample review markdown (subset of the real /pr-review output format)
# ---------------------------------------------------------------------------

SAMPLE_REVIEW = """\
# PR Review: #417 - perf(imbue): bounded-reads parallel safety

**Verdict:** Request changes
**Blocking:** 3 | **Non-blocking:** 2 | **ADR violations:** 0

## Blocking findings

### B1 - AI-attribution regex false-positives on bare URL/domain matches

`plugins/imbue/hooks/vow_no_ai_attribution.py:31-32`

The bare `claude.ai` and `anthropic.com` patterns false-positive on
legitimate URL mentions in commit messages.

Suggested direction: scope the URL patterns to attribution contexts.

### B2 - 50-thread atomicity test passes without flock due to GIL

`plugins/imbue/tests/unit/hooks/test_vow_bounded_reads.py:631-672`

CPython's GIL serializes the JSON parse-modify-write inside
`_atomic_increment` at the bytecode level.

Suggested direction: inject a deterministic race.

## Non-blocking findings

| ID | Source | Where | Concern |
|----|--------|-------|---------|
| NB1 | Security | `vow_bounded_reads.py:119` | flock failure swallowed silently |
| NB2 | Security | `validators/markdown_wrap.py:160` | open(path) on caller paths |

---

*Review generated by 4-agent parallel dispatch.*
"""


class TestExtractVerdict:
    """Feature: Pull the verdict line from review markdown."""

    @pytest.mark.unit
    def test_extracts_verdict_line(self) -> None:
        """Scenario: '**Verdict:** Request changes' is recognized."""
        assert extract_verdict(SAMPLE_REVIEW) == "Request changes"

    @pytest.mark.unit
    def test_missing_verdict_returns_unknown(self) -> None:
        """Scenario: No verdict line"""
        assert extract_verdict("# nope\n") == "unknown"


class TestExtractBlockers:
    """Feature: Parse Blocking findings into structured records."""

    @pytest.mark.unit
    def test_finds_two_blockers(self) -> None:
        blockers = extract_blockers(SAMPLE_REVIEW)
        assert len(blockers) == 2
        assert blockers[0]["id"] == "B1"
        assert "AI-attribution regex" in blockers[0]["title"]
        assert "vow_no_ai_attribution.py:31-32" in blockers[0]["body"]

    @pytest.mark.unit
    def test_empty_review_returns_empty(self) -> None:
        assert extract_blockers("# nothing\n") == []


class TestExtractNonBlocking:
    """Feature: Parse the Non-blocking table into rows."""

    @pytest.mark.unit
    def test_finds_table_rows(self) -> None:
        rows = extract_non_blocking(SAMPLE_REVIEW)
        assert len(rows) == 2
        assert rows[0]["id"] == "NB1"
        assert "vow_bounded_reads.py:119" in rows[0]["where"]

    @pytest.mark.unit
    def test_no_table_returns_empty(self) -> None:
        assert extract_non_blocking("no table here\n") == []


class TestParseReviewMarkdown:
    """Feature: Combined parser produces a structured ReviewSummary."""

    @pytest.mark.unit
    def test_returns_complete_summary(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        assert summary.verdict == "Request changes"
        assert len(summary.blockers) == 2
        assert len(summary.non_blocking) == 2


class TestReviewToFindings:
    """Feature: ReviewSummary -> list[Finding] for post_findings()."""

    @pytest.mark.unit
    def test_each_blocker_becomes_a_finding(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        findings = review_to_findings(summary, pr_number=417)
        # Two blockers + two non-blocking = 4 findings.
        assert len(findings) == 4
        first = findings[0]
        assert first.type == "PR Finding"
        assert first.severity == "high"  # blockers are high
        assert "B1" in first.summary

    @pytest.mark.unit
    def test_finding_includes_pr_link_in_evidence(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        findings = review_to_findings(summary, pr_number=417)
        assert any("#417" in f.evidence for f in findings)

    @pytest.mark.unit
    def test_non_blocking_marked_medium(self) -> None:
        summary = parse_review_markdown(SAMPLE_REVIEW)
        findings = review_to_findings(summary, pr_number=417)
        nb = [f for f in findings if f.summary.startswith("NB")]
        assert nb
        assert all(f.severity == "medium" for f in nb)


class TestMain:
    """Feature: CLI entry point reads file, posts findings."""

    @pytest.mark.unit
    def test_main_skips_when_no_findings(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        empty = tmp_path / "empty.md"
        empty.write_text("# nothing\n")
        monkeypatch.setattr(sys, "argv", ["post_review_insights.py", str(empty)])
        with pytest.raises(SystemExit) as exc:
            main()
        assert exc.value.code == 0

    @pytest.mark.unit
    def test_main_calls_post_findings_when_findings_found(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        review = tmp_path / "pr-417-review.md"
        review.write_text(SAMPLE_REVIEW)
        monkeypatch.setattr(sys, "argv", ["post_review_insights.py", str(review)])

        with patch("post_review_insights.post_findings") as mock_post:
            mock_post.return_value = ["https://example.com/d/1"]
            with pytest.raises(SystemExit) as exc:
                main()
            assert exc.value.code == 0
            mock_post.assert_called_once()
            posted_findings = mock_post.call_args[0][0]
            assert len(posted_findings) == 4  # 2 blockers + 2 non-blocking

    @pytest.mark.unit
    def test_main_missing_file_exits_nonzero(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(sys, "argv", ["post_review_insights.py", "/nonexistent.md"])
        with pytest.raises(SystemExit) as exc:
            main()
        assert exc.value.code != 0
