"""Tests for discussion_enrichment.

Feature: Enriched Phase 6a Collective Intelligence posts
    As a maintainer reading auto-generated Learning posts
    I want surfaced Detail/Recent Errors, lens-driven recommendations,
    failure-mode names, trends, and action items
    So that posts deliver actionable insight rather than just symptoms
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Add scripts directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "scripts"))

from discussion_enrichment import (  # noqa: E402 - sys.path adjusted above to discover scripts dir
    EnrichedIssue,
    FailureMode,
    cluster_failure_modes,
    compute_trend_deltas,
    errors_by_skill_from_issues,
    format_action_items,
    format_enriched_issues,
    format_failure_modes,
    format_lens_findings,
    format_perf_summary,
    format_persistence_callout,
    format_trends,
    generate_action_items,
    parse_enriched_issues,
    parse_perf_summary,
    rank_findings,
    run_lenses,
    track_issue_persistence,
)
from insight_types import (
    Finding,  # noqa: E402 - sys.path adjusted above to discover scripts dir
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


SAMPLE_LEARNINGS = """\
# Skill Performance Learnings

**Last Updated**: 2026-04-23 18:52:32 UTC
**Analysis Period**: Last 30 days
**Skills Analyzed**: 2
**Total Executions**: 60

---

## High-Impact Issues

Skills with significant problems requiring immediate attention.

### abstract:skill-auditor
**Type**: high_failure_rate
**Severity**: high
**Metric**: 40.0% success rate
**Detail**: 24/40 failures
**Recent Errors**:
- Error: validation failed on schema field 'description'
- Error: validation failed on missing frontmatter
- Error: validation failed on schema field 'name'

### sanctum:pr-prep
**Type**: slow_execution
**Severity**: medium
**Metric**: avg 12.4s
**Detail**: max 45s on 20 runs

---

## Skill Performance Summary

| Skill | Executions | Success Rate | Avg Duration | Rating |
|-------|------------|--------------|--------------|--------|
| `abstract:skill-auditor` | 40 | 40.0% | 0.1s | N/A |
| `sanctum:pr-prep` | 20 | 90.0% | 12.4s | 4.1 |

---

*Generated by aggregate_skill_logs.py (Issue #69 Phase 3)*
"""


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------


class TestParseEnrichedIssues:
    """Feature: Parse High-Impact Issues with Detail + Recent Errors

    As a poster
    I want every field LEARNINGS.md exposes per issue
    So that the discussion can show the full diagnosis
    """

    @pytest.mark.unit
    def test_extracts_skill_type_severity_metric_detail(self) -> None:
        """Scenario: Full field extraction
        Given LEARNINGS.md with two issues
        When parse_enriched_issues runs
        Then both issues have all five primary fields populated
        """
        issues = parse_enriched_issues(SAMPLE_LEARNINGS)
        assert len(issues) == 2
        first = issues[0]
        assert first.skill == "abstract:skill-auditor"
        assert first.issue_type == "high_failure_rate"
        assert first.severity == "high"
        assert first.metric == "40.0% success rate"
        assert first.detail == "24/40 failures"

    @pytest.mark.unit
    def test_extracts_recent_errors_bullets(self) -> None:
        """Scenario: Recent Errors bullets are surfaced
        Given an issue with three Recent Errors bullets
        When parsed
        Then all three appear in recent_errors
        """
        issues = parse_enriched_issues(SAMPLE_LEARNINGS)
        first = issues[0]
        assert len(first.recent_errors) == 3
        assert "schema field 'description'" in first.recent_errors[0]
        assert "missing frontmatter" in first.recent_errors[1]

    @pytest.mark.unit
    def test_issue_without_recent_errors_returns_empty_list(self) -> None:
        """Scenario: Issue lacks Recent Errors
        Given an issue with no Recent Errors block
        When parsed
        Then recent_errors is an empty list, not None
        """
        issues = parse_enriched_issues(SAMPLE_LEARNINGS)
        second = issues[1]  # sanctum:pr-prep has no Recent Errors
        assert second.recent_errors == []

    @pytest.mark.unit
    def test_no_high_impact_section_returns_empty(self) -> None:
        """Scenario: No issues to surface
        Given a LEARNINGS.md without High-Impact Issues section
        When parsed
        Then result is empty list
        """
        assert parse_enriched_issues("# Empty\n\nNothing here.\n") == []


class TestParsePerfSummary:
    """Feature: Parse Skill Performance Summary table"""

    @pytest.mark.unit
    def test_extracts_table_rows(self) -> None:
        """Scenario: Two-row performance table
        Given the sample LEARNINGS.md with two skills in the table
        When parse_perf_summary runs
        Then both rows are returned with their five columns
        """
        rows = parse_perf_summary(SAMPLE_LEARNINGS)
        assert len(rows) == 2
        assert rows[0]["skill"] == "abstract:skill-auditor"
        assert rows[0]["executions"] == "40"
        assert rows[0]["success_rate"] == "40.0%"
        assert rows[1]["skill"] == "sanctum:pr-prep"
        assert rows[1]["rating"] == "4.1"

    @pytest.mark.unit
    def test_no_table_returns_empty(self) -> None:
        """Scenario: Missing performance table
        Given LEARNINGS.md without a performance table
        When parsed
        Then result is empty list
        """
        assert parse_perf_summary("# nope\n") == []


# ---------------------------------------------------------------------------
# Failure mode clustering
# ---------------------------------------------------------------------------


class TestClusterFailureModes:
    """Feature: Cluster similar errors into named failure modes

    As a reader
    I want errors with shared significant terms grouped under one name
    So that 24 individual "validation failed" lines become one named mode
    """

    @pytest.mark.unit
    def test_groups_errors_sharing_significant_terms(self) -> None:
        """Scenario: Three errors all mention 'frontmatter'
        Given errors_by_skill with three frontmatter-related errors
        When cluster_failure_modes runs
        Then one FailureMode is returned named after the dominant term
        """
        errors = {
            "abstract:skill-auditor": [
                "validation failed missing frontmatter description",
                "validation failed missing frontmatter name",
            ],
            "abstract:rules-eval": [
                "validation failed missing frontmatter trigger",
            ],
        }
        modes = cluster_failure_modes(errors)
        assert len(modes) == 1
        mode = modes[0]
        assert mode.name in {"frontmatter", "missing", "validation"}
        assert mode.occurrences == 3
        assert "abstract:skill-auditor" in mode.skills
        assert "abstract:rules-eval" in mode.skills

    @pytest.mark.unit
    def test_singleton_errors_do_not_form_a_mode(self) -> None:
        """Scenario: Each skill has unique errors
        Given errors with no shared terms across skills
        When clustered
        Then no FailureMode is produced (below MIN_ERRORS threshold)
        """
        errors = {
            "skill:a": ["network timeout to upstream"],
            "skill:b": ["division by zero in calculator"],
        }
        modes = cluster_failure_modes(errors)
        assert modes == []

    @pytest.mark.unit
    def test_empty_input_returns_empty(self) -> None:
        """Scenario: No errors to cluster
        Given an empty errors_by_skill dict
        When clustered
        Then result is empty list
        """
        assert cluster_failure_modes({}) == []


# ---------------------------------------------------------------------------
# Lens runner
# ---------------------------------------------------------------------------


class TestRunLenses:
    """Feature: Wire existing lenses into the discussion poster

    As a poster
    I want the existing pattern/delta/health/trend lenses run automatically
    So that their Finding.recommendation values reach the discussion
    """

    @pytest.mark.unit
    def test_runs_without_metrics_returns_empty(self) -> None:
        """Scenario: Empty metrics dict
        Given no metrics
        When run_lenses runs
        Then it returns an empty list (lenses should bail gracefully)
        """
        assert run_lenses({}) == []

    @pytest.mark.unit
    def test_returns_findings_for_real_skill_summary(self) -> None:
        """Scenario: Real metrics produce findings
        Given two SkillLogSummary objects with shared error terms
        When run_lenses runs
        Then at least one Finding is returned (pattern lens fires)
        """
        # Use the real SkillLogSummary so the lens contract is honored.
        from aggregate_skill_logs import SkillLogSummary

        metrics = {
            "abstract:skill-auditor": SkillLogSummary(
                skill="abstract:skill-auditor",
                plugin="abstract",
                skill_name="skill-auditor",
                total_executions=40,
                success_count=16,
                failure_count=24,
                partial_count=0,
                avg_duration_ms=100.0,
                max_duration_ms=300,
                success_rate=40.0,
                avg_rating=None,
                common_friction=[],
                improvement_suggestions=[],
                recent_errors=[
                    "validation failed frontmatter missing description",
                    "validation failed frontmatter missing name",
                ],
            ),
            "abstract:rules-eval": SkillLogSummary(
                skill="abstract:rules-eval",
                plugin="abstract",
                skill_name="rules-eval",
                total_executions=20,
                success_count=15,
                failure_count=5,
                partial_count=0,
                avg_duration_ms=80.0,
                max_duration_ms=200,
                success_rate=75.0,
                avg_rating=None,
                common_friction=[],
                improvement_suggestions=[],
                recent_errors=[
                    "validation failed frontmatter missing trigger",
                ],
            ),
        }
        findings = run_lenses(metrics)
        # Pattern lens should fire on shared frontmatter errors.
        # Even if not, this asserts the runner does not crash.
        assert isinstance(findings, list)
        for f in findings:
            assert isinstance(f, Finding)


class TestRankFindings:
    """Feature: Rank findings by severity"""

    @pytest.mark.unit
    def test_high_severity_comes_first(self) -> None:
        """Scenario: Three findings with mixed severity
        Given low, high, and medium findings in random order
        When ranked
        Then high comes first, then medium, then low
        """
        findings = [
            _finding(severity="low"),
            _finding(severity="high"),
            _finding(severity="medium"),
        ]
        ranked = rank_findings(findings)
        assert [f.severity for f in ranked] == ["high", "medium", "low"]


# ---------------------------------------------------------------------------
# Trend deltas
# ---------------------------------------------------------------------------


class TestComputeTrendDeltas:
    """Feature: Compare current snapshot to previous

    As a reader
    I want to know what changed since last post
    So that I can spot regressions and improvements at a glance
    """

    @pytest.mark.unit
    def test_no_previous_snapshot_returns_all_as_new(self) -> None:
        """Scenario: First post ever
        Given no previous snapshot
        When deltas computed
        Then all current skills are 'new'
        """
        current = {"a": {"success_rate": 90, "total_executions": 10}}
        deltas = compute_trend_deltas(current, None)
        assert deltas["new_skills"] == ["a"]
        assert deltas["resolved_skills"] == []

    @pytest.mark.unit
    def test_significant_rate_change_recorded(self) -> None:
        """Scenario: Success rate dropped 30 percentage points
        Given previous=70, current=40
        When deltas computed
        Then a rate_change entry appears with delta=-30
        """
        prev = {"a": {"success_rate": 70, "total_executions": 100}}
        cur = {"a": {"success_rate": 40, "total_executions": 100}}
        deltas = compute_trend_deltas(cur, prev)
        assert any(
            c["skill"] == "a" and c["delta"] == -30 for c in deltas["rate_changes"]
        )

    @pytest.mark.unit
    def test_small_rate_change_filtered_out(self) -> None:
        """Scenario: 2pp change is noise
        Given previous=70, current=72
        When deltas computed
        Then no rate_changes entry is produced
        """
        prev = {"a": {"success_rate": 70, "total_executions": 100}}
        cur = {"a": {"success_rate": 72, "total_executions": 100}}
        deltas = compute_trend_deltas(cur, prev)
        assert deltas["rate_changes"] == []

    @pytest.mark.unit
    def test_skill_disappearance_recorded_as_resolved(self) -> None:
        """Scenario: Previous had skill 'b', current does not
        Given previous={a, b}, current={a}
        When deltas computed
        Then 'b' is in resolved_skills
        """
        prev = {
            "a": {"success_rate": 90, "total_executions": 10},
            "b": {"success_rate": 50, "total_executions": 5},
        }
        cur = {"a": {"success_rate": 90, "total_executions": 10}}
        deltas = compute_trend_deltas(cur, prev)
        assert deltas["resolved_skills"] == ["b"]


# ---------------------------------------------------------------------------
# Action items + persistence
# ---------------------------------------------------------------------------


class TestGenerateActionItems:
    """Feature: Convert findings to checkbox action items"""

    @pytest.mark.unit
    def test_findings_become_checkboxes_with_skill(self) -> None:
        """Scenario: Finding with skill and recommendation
        Given a single Finding with skill='myskill' and recommendation='Fix it'
        When action items generated
        Then output contains a markdown checkbox with skill bolded
        """
        findings = [_finding(skill="myskill", recommendation="Fix it now")]
        items = generate_action_items(findings)
        assert any("**myskill**" in item and "Fix it now" in item for item in items)
        assert all(item.startswith("- [ ]") for item in items)

    @pytest.mark.unit
    def test_persistent_issues_become_file_issue_items(self) -> None:
        """Scenario: Persistent issue triggers file-issue action
        Given persistent=[{skill, issue_type, streak}]
        When action items generated
        Then a 'File a tracking issue' item is included
        """
        items = generate_action_items(
            findings=[],
            persistent=[
                {
                    "skill": "abstract:skill-auditor",
                    "issue_type": "high_failure_rate",
                    "streak": 3,
                }
            ],
        )
        assert any("File a tracking issue" in item for item in items)
        assert any("3 consecutive posts" in item for item in items)

    @pytest.mark.unit
    def test_no_data_yields_continue_monitoring(self) -> None:
        """Scenario: Nothing to act on
        Given no findings and no persistent issues
        When action items generated
        Then output is a single 'continue monitoring' line
        """
        items = generate_action_items([])
        assert len(items) == 1
        assert "Continue monitoring" in items[0]


class TestTrackIssuePersistence:
    """Feature: Detect issues persisting across N posts"""

    @pytest.mark.unit
    def test_issue_in_all_recent_history_is_persistent(self) -> None:
        """Scenario: Same issue in last two posts plus today
        Given threshold=3 and history showing the same fingerprint twice
        When tracked
        Then the issue is flagged as persistent
        """
        issues = [
            EnrichedIssue(
                skill="a:b",
                issue_type="failure_rate",
                severity="high",
                metric="",
                detail="",
            )
        ]
        history = [
            ["a:b|failure_rate", "other:thing|x"],
            ["a:b|failure_rate"],
        ]
        result = track_issue_persistence(issues, history, threshold=3)
        assert len(result) == 1
        assert result[0]["skill"] == "a:b"
        assert result[0]["streak"] == 3

    @pytest.mark.unit
    def test_issue_missing_from_recent_history_not_flagged(self) -> None:
        """Scenario: Issue is new today
        Given history without this issue's fingerprint
        When tracked with threshold=3
        Then result is empty
        """
        issues = [
            EnrichedIssue(
                skill="a:b", issue_type="t", severity="high", metric="", detail=""
            )
        ]
        history = [["other|other"], ["other|other"]]
        assert track_issue_persistence(issues, history, threshold=3) == []

    @pytest.mark.unit
    def test_threshold_below_2_returns_empty(self) -> None:
        """Scenario: Invalid threshold
        Given threshold=1 (would mean 'persistent if seen once')
        When tracked
        Then empty list (degenerate case)
        """
        issues = [
            EnrichedIssue(
                skill="a", issue_type="t", severity="high", metric="", detail=""
            )
        ]
        assert track_issue_persistence(issues, [["a|t"]], threshold=1) == []


# ---------------------------------------------------------------------------
# Section formatters (smoke tests for shape, not exact output)
# ---------------------------------------------------------------------------


class TestSectionFormatters:
    """Feature: Format each section with the correct heading + content"""

    @pytest.mark.unit
    def test_format_enriched_issues_includes_detail_and_errors(self) -> None:
        issues = parse_enriched_issues(SAMPLE_LEARNINGS)
        out = format_enriched_issues(issues)
        assert "## Top Issues" in out
        assert "**Detail**: 24/40 failures" in out
        assert "schema field 'description'" in out

    @pytest.mark.unit
    def test_format_perf_summary_renders_table(self) -> None:
        rows = parse_perf_summary(SAMPLE_LEARNINGS)
        out = format_perf_summary(rows)
        assert "## Performance Summary" in out
        assert "| `abstract:skill-auditor` | 40 |" in out

    @pytest.mark.unit
    def test_format_failure_modes_includes_count_and_sample(self) -> None:
        modes = [
            FailureMode(
                name="frontmatter",
                skills=["a:b", "c:d"],
                sample_error="validation failed frontmatter missing",
                occurrences=3,
            )
        ]
        out = format_failure_modes(modes)
        assert "`frontmatter`" in out
        assert "3 occurrences" in out
        assert "`a:b`" in out

    @pytest.mark.unit
    def test_format_lens_findings_includes_recommendation(self) -> None:
        findings = [_finding(recommendation="Do the thing")]
        out = format_lens_findings(findings)
        assert "## Insights & Recommendations" in out
        assert "Do the thing" in out

    @pytest.mark.unit
    def test_format_trends_renders_changes(self) -> None:
        deltas = {
            "rate_changes": [{"skill": "a", "delta": -30, "now": 40}],
            "exec_changes": [],
            "new_skills": ["b"],
            "resolved_skills": [],
        }
        out = format_trends(deltas)
        assert "Trends vs Previous Snapshot" in out
        assert "-30pp" in out
        assert "`b`" in out

    @pytest.mark.unit
    def test_format_action_items_concatenates(self) -> None:
        out = format_action_items(["- [ ] one", "- [ ] two"])
        assert "## Action Items" in out
        assert "- [ ] one" in out
        assert "- [ ] two" in out

    @pytest.mark.unit
    def test_format_persistence_callout_lists_streaks(self) -> None:
        out = format_persistence_callout(
            [{"skill": "a:b", "issue_type": "x", "streak": 3}]
        )
        assert "Persistent Issues" in out
        assert "3 consecutive" in out

    @pytest.mark.unit
    def test_empty_inputs_yield_empty_strings(self) -> None:
        """Empty data => empty string so the composer can skip sections cleanly."""
        assert format_enriched_issues([]) == ""
        assert format_perf_summary([]) == ""
        assert format_failure_modes([]) == ""
        assert format_lens_findings([]) == ""
        assert format_trends({}) == ""
        assert format_action_items([]) == ""
        assert format_persistence_callout([]) == ""


class TestErrorsBySkillFromIssues:
    """Feature: Pivot EnrichedIssue list into the lens-shaped dict"""

    @pytest.mark.unit
    def test_groups_errors_by_skill(self) -> None:
        issues = [
            EnrichedIssue(
                skill="a:b",
                issue_type="t",
                severity="high",
                metric="",
                detail="",
                recent_errors=["e1"],
            ),
            EnrichedIssue(
                skill="a:b",
                issue_type="u",
                severity="medium",
                metric="",
                detail="",
                recent_errors=["e2"],
            ),
        ]
        result = errors_by_skill_from_issues(issues)
        assert result["a:b"] == ["e1", "e2"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _finding(
    *,
    severity: str = "medium",
    skill: str = "",
    recommendation: str = "Investigate.",
    summary: str = "Summary",
    type_: str = "Pattern",
    source: str = "test-lens",
    evidence: str = "",
) -> Finding:
    return Finding(
        type=type_,
        severity=severity,
        skill=skill,
        summary=summary,
        evidence=evidence,
        recommendation=recommendation,
        source=source,
    )
