"""Tests for auto_promote_learnings.py.

Covers priority scoring, LEARNINGS.md parsing, GitHub issue/discussion
creation, and the main run_auto_promote pipeline.
"""

from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "scripts"))
import auto_promote_learnings as apl

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SAMPLE_LEARNINGS = """# Skill Performance Learnings

**Last Updated**: 2024-01-15 12:00:00 UTC
**Analysis Period**: Last 30 days
**Skills Analyzed**: 5
**Total Executions**: 120

---

## High-Impact Issues

### abstract:skill-auditor
**Type**: high_failure_rate
**Severity**: high
**Metric**: 20.0% success rate
**Detail**: 8/10 failures

### abstract:bad-skill
**Type**: low_rating
**Severity**: medium
**Metric**: 2.5/5.0 rating
**Detail**: User evaluations indicate poor effectiveness

---

## Slow Execution

| Skill | Avg Duration | Max Duration | Executions |
|-------|--------------|--------------|------------|
| `abstract:slow-skill` | 15.0s | 30.0s | 5 |

---

## Low User Ratings

### abstract:bad-skill - 2.5/5.0
**Common Friction**:
- unclear output

---

## Skill Performance Summary

| Skill | Executions | Success Rate | Avg Duration | Rating |
|-------|------------|--------------|--------------|--------|
| `abstract:skill-auditor` | 10 | 20.0% | 2.0s | N/A |
| `abstract:bad-skill` | 8 | 90.0% | 1.0s | 2.5/5.0 |
| `abstract:slow-skill` | 5 | 95.0% | 15.0s | N/A |

*Generated by aggregate_skill_logs.py*
"""


# ---------------------------------------------------------------------------
# PromotedIssueRecord
# ---------------------------------------------------------------------------


class TestPromotedIssueRecord:
    """PromotedIssueRecord persists promoted items."""

    @pytest.mark.unit
    def test_new_record_is_empty(self, tmp_path):
        """When no record file exists, promoted dict is empty."""
        record = apl.PromotedIssueRecord.load(tmp_path / "promoted.json")
        assert record.promoted == {}

    @pytest.mark.unit
    def test_is_promoted_false_for_unknown_key(self, tmp_path):
        """is_promoted returns False for an unknown key."""
        record = apl.PromotedIssueRecord.load(tmp_path / "promoted.json")
        assert not record.is_promoted("p:s:high_failure_rate")

    @pytest.mark.unit
    def test_add_and_is_promoted(self, tmp_path):
        """After add(), is_promoted returns True."""
        record = apl.PromotedIssueRecord()
        record.add("p:s:high_failure_rate", "https://example.com/1")
        assert record.is_promoted("p:s:high_failure_rate")

    @pytest.mark.unit
    def test_save_and_reload(self, tmp_path):
        """Save followed by load gives the same record."""
        path = tmp_path / "promoted.json"
        record = apl.PromotedIssueRecord()
        record.add("p:s:type", "https://url")
        record.save(path)

        reloaded = apl.PromotedIssueRecord.load(path)
        assert reloaded.is_promoted("p:s:type")
        assert reloaded.promoted["p:s:type"] == "https://url"

    @pytest.mark.unit
    def test_bad_json_returns_empty(self, tmp_path):
        """Malformed JSON file returns empty record."""
        path = tmp_path / "promoted.json"
        path.write_text("INVALID")
        record = apl.PromotedIssueRecord.load(path)
        assert record.promoted == {}


# ---------------------------------------------------------------------------
# calculate_priority
# ---------------------------------------------------------------------------


class TestCalculatePriority:
    """calculate_priority computes (Frequency x Impact) / Ease."""

    @pytest.mark.unit
    def test_high_failure_rate_high_impact(self):
        """High failure rate yields non-trivial score."""
        item = {
            "type": "high_failure_rate",
            "severity": "high",
            "executions": 10,
            "success_rate": 0.0,  # 0% success = max impact
        }
        score = apl.calculate_priority(item)
        assert score > apl.HIGH_PRIORITY_THRESHOLD

    @pytest.mark.unit
    def test_low_rating_score(self):
        """Low rating yields positive score based on gap from 5.0."""
        item = {
            "type": "low_rating",
            "severity": "medium",
            "executions": 5,
            "avg_rating": 2.0,
        }
        score = apl.calculate_priority(item)
        # Impact = (5.0 - 2.0) * 2 = 6.0; ease = 3.0; freq = 5
        assert score == pytest.approx(5 * 6.0 / 3.0)

    @pytest.mark.unit
    def test_slow_execution_score(self):
        """Slow execution item yields score proportional to seconds over threshold."""
        item = {
            "type": "slow_execution",
            "severity": "medium",
            "executions": 5,
            "avg_duration_ms": 20000,  # 10s over threshold
        }
        score = apl.calculate_priority(item)
        # seconds_over = 10; impact = 1.0; ease = 3.0; freq = 5
        assert score == pytest.approx(5 * 1.0 / 3.0)

    @pytest.mark.unit
    def test_excessive_failures_fixed_high_impact(self):
        """Excessive failures use fixed impact of 8.0."""
        item = {
            "type": "excessive_failures",
            "severity": "high",
            "executions": 5,
        }
        score = apl.calculate_priority(item)
        # impact = 8.0; ease = 2.0; freq = 5
        assert score == pytest.approx(5 * 8.0 / 2.0)

    @pytest.mark.unit
    def test_unknown_type_minimal_impact(self):
        """Unknown type yields minimal positive score."""
        item = {
            "type": "unknown",
            "severity": "low",
            "executions": 1,
        }
        score = apl.calculate_priority(item)
        assert score > 0
        assert score < 1.0

    @pytest.mark.unit
    def test_zero_executions_defaults_to_one(self):
        """Zero executions defaults to frequency=1 to avoid zero scores."""
        item = {"type": "high_failure_rate", "severity": "high", "success_rate": 0.0}
        score_no_exec = apl.calculate_priority(item)
        item_with_exec = {
            "type": "high_failure_rate",
            "severity": "high",
            "executions": 1,
            "success_rate": 0.0,
        }
        score_one_exec = apl.calculate_priority(item_with_exec)
        assert score_no_exec == score_one_exec


# ---------------------------------------------------------------------------
# _parse_summary_table
# ---------------------------------------------------------------------------


class TestParseSummaryTable:
    """_parse_summary_table extracts per-skill metrics from the performance table."""

    @pytest.mark.unit
    def test_extracts_skill_metrics(self):
        """Skill row is parsed with executions, success_rate, avg_duration."""
        metrics = apl._parse_summary_table(SAMPLE_LEARNINGS)
        assert "abstract:skill-auditor" in metrics
        entry = metrics["abstract:skill-auditor"]
        assert entry["executions"] == 10
        assert entry["success_rate"] == pytest.approx(20.0)

    @pytest.mark.unit
    def test_rating_parsed_when_present(self):
        """Rating is extracted when in 'X.X/5.0' format."""
        metrics = apl._parse_summary_table(SAMPLE_LEARNINGS)
        assert metrics["abstract:bad-skill"]["avg_rating"] == pytest.approx(2.5)

    @pytest.mark.unit
    def test_rating_none_when_na(self):
        """Rating is None when column shows 'N/A'."""
        metrics = apl._parse_summary_table(SAMPLE_LEARNINGS)
        assert metrics["abstract:skill-auditor"]["avg_rating"] is None

    @pytest.mark.unit
    def test_empty_content_returns_empty(self):
        """Empty content returns empty dict."""
        assert apl._parse_summary_table("") == {}


# ---------------------------------------------------------------------------
# parse_improvement_items
# ---------------------------------------------------------------------------


class TestParseImprovementItems:
    """parse_improvement_items extracts all promotable items."""

    @pytest.mark.unit
    def test_empty_content_returns_empty(self):
        """Empty content returns empty list."""
        assert apl.parse_improvement_items("") == []

    @pytest.mark.unit
    def test_high_impact_issues_extracted(self):
        """Items from High-Impact Issues section are returned."""
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        skills = [i["skill"] for i in items]
        assert "abstract:skill-auditor" in skills

    @pytest.mark.unit
    def test_slow_skill_extracted(self):
        """Items from Slow Execution section are returned."""
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        skills = [i["skill"] for i in items]
        assert "abstract:slow-skill" in skills

    @pytest.mark.unit
    def test_slow_skill_not_duplicated_if_already_in_high_impact(self):
        """Skills already in high-impact aren't duplicated from slow section."""
        # abstract:skill-auditor is in high-impact, not slow; abstract:slow-skill
        # is only in slow, so it should appear exactly once
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        slow_items = [i for i in items if i["skill"] == "abstract:slow-skill"]
        assert len(slow_items) == 1

    @pytest.mark.unit
    def test_low_rated_skill_extracted_or_merged(self):
        """Low-rated skill is either extracted or merged into existing item."""
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        bad_skill_items = [i for i in items if i["skill"] == "abstract:bad-skill"]
        assert len(bad_skill_items) >= 1

    @pytest.mark.unit
    def test_items_have_required_fields(self):
        """Each item has 'skill', 'type', 'severity' fields."""
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        for item in items:
            assert "skill" in item
            assert "type" in item
            assert "severity" in item

    @pytest.mark.unit
    def test_enriched_with_summary_metrics(self):
        """High-impact items are enriched with executions from summary table."""
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        auditor = next(
            (i for i in items if i["skill"] == "abstract:skill-auditor"), None
        )
        assert auditor is not None
        assert auditor.get("executions") == 10


# ---------------------------------------------------------------------------
# has_existing_issue
# ---------------------------------------------------------------------------


class TestHasExistingIssue:
    """has_existing_issue checks GitHub for duplicate issues."""

    @pytest.mark.unit
    def test_returns_true_when_issue_found(self):
        """Returns True when gh issue list returns a result."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = '[{"number": 42}]'

        with patch("subprocess.run", return_value=mock_result):
            result = apl.has_existing_issue(
                {"skill": "p:s", "type": "high_failure_rate"},
                "owner/repo",
            )

        assert result is True

    @pytest.mark.unit
    def test_returns_false_when_no_issues(self):
        """Returns False when gh issue list returns empty list."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "[]"

        with patch("subprocess.run", return_value=mock_result):
            result = apl.has_existing_issue(
                {"skill": "p:s", "type": "high_failure_rate"},
                "owner/repo",
            )

        assert result is False

    @pytest.mark.unit
    def test_returns_false_on_gh_error(self):
        """Returns False when gh command fails."""
        mock_result = MagicMock()
        mock_result.returncode = 1

        with patch("subprocess.run", return_value=mock_result):
            result = apl.has_existing_issue(
                {"skill": "p:s", "type": "high_failure_rate"},
                "owner/repo",
            )

        assert result is False

    @pytest.mark.unit
    def test_returns_false_on_exception(self):
        """Returns False when subprocess raises."""
        with patch("subprocess.run", side_effect=Exception("boom")):
            result = apl.has_existing_issue(
                {"skill": "p:s", "type": "high_failure_rate"},
                "owner/repo",
            )

        assert result is False


# ---------------------------------------------------------------------------
# promote_to_issue
# ---------------------------------------------------------------------------


class TestPromoteToIssue:
    """promote_to_issue creates GitHub issues for high-priority items."""

    @pytest.mark.unit
    def test_returns_url_on_success(self):
        """Returns URL when gh issue create succeeds."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "https://github.com/issues/1\n"

        item = {
            "skill": "p:s",
            "type": "high_failure_rate",
            "metric": "20%",
            "detail": "8/10 failures",
        }
        with patch("subprocess.run", return_value=mock_result):
            url = apl.promote_to_issue(item, "owner/repo")

        assert url == "https://github.com/issues/1"

    @pytest.mark.unit
    def test_returns_none_on_gh_failure(self, capsys):
        """Returns None when gh issue create fails."""
        mock_result = MagicMock()
        mock_result.returncode = 1
        mock_result.stderr = "auth error"

        item = {"skill": "p:s", "type": "x", "metric": "y", "detail": "z"}
        with patch("subprocess.run", return_value=mock_result):
            url = apl.promote_to_issue(item, "owner/repo")

        assert url is None

    @pytest.mark.unit
    def test_returns_none_when_gh_not_found(self):
        """Returns None when gh CLI is not installed."""
        item = {"skill": "p:s", "type": "x", "metric": "y", "detail": "z"}
        with patch("subprocess.run", side_effect=FileNotFoundError):
            url = apl.promote_to_issue(item, "owner/repo")

        assert url is None

    @pytest.mark.unit
    def test_returns_none_on_unexpected_exception(self):
        """Returns None on any unexpected exception."""
        item = {"skill": "p:s", "type": "x", "metric": "y", "detail": "z"}
        with patch("subprocess.run", side_effect=RuntimeError("boom")):
            url = apl.promote_to_issue(item, "owner/repo")

        assert url is None


# ---------------------------------------------------------------------------
# post_to_discussion
# ---------------------------------------------------------------------------


class TestPostToDiscussion:
    """post_to_discussion posts medium-severity items to Discussions."""

    @pytest.mark.unit
    def test_returns_url_on_success(self, tmp_path, monkeypatch):
        """Returns URL when discussion creation succeeds."""
        import post_learnings_to_discussions as pld

        monkeypatch.setattr(pld, "get_config_dir", lambda: tmp_path)

        item = {
            "skill": "p:s",
            "type": "low_rating",
            "metric": "2.5/5.0",
            "detail": "bad",
        }

        with (
            patch.object(apl, "resolve_category_id", return_value="CAT_ID"),
            patch.object(apl, "PostedRecord") as mock_rec_cls,
            patch.object(apl, "get_repo_node_id", return_value="REPO_ID"),
            patch.object(
                apl, "create_discussion", return_value="https://github.com/d/1"
            ),
        ):
            mock_rec_cls.load.return_value = MagicMock()
            url = apl.post_to_discussion(item, "owner", "repo")

        assert url == "https://github.com/d/1"

    @pytest.mark.unit
    def test_returns_none_when_no_category(self, tmp_path, monkeypatch):
        """Returns None when no 'learnings' category found."""
        import post_learnings_to_discussions as pld

        monkeypatch.setattr(pld, "get_config_dir", lambda: tmp_path)

        item = {
            "skill": "p:s",
            "type": "low_rating",
            "metric": "2.5/5.0",
            "detail": "bad",
        }

        with patch.object(apl, "resolve_category_id", return_value=None):
            url = apl.post_to_discussion(item, "owner", "repo")

        assert url is None

    @pytest.mark.unit
    def test_returns_none_on_exception(self, tmp_path, monkeypatch):
        """Returns None when an exception is raised."""
        import post_learnings_to_discussions as pld

        monkeypatch.setattr(pld, "get_config_dir", lambda: tmp_path)

        item = {
            "skill": "p:s",
            "type": "low_rating",
            "metric": "2.5/5.0",
            "detail": "bad",
        }

        with patch.object(apl, "resolve_category_id", side_effect=Exception("boom")):
            url = apl.post_to_discussion(item, "owner", "repo")

        assert url is None


# ---------------------------------------------------------------------------
# run_auto_promote (main pipeline)
# ---------------------------------------------------------------------------


class TestRunAutoPromote:
    """run_auto_promote orchestrates the full pipeline."""

    @pytest.mark.unit
    def test_returns_empty_when_no_learnings_file(self, tmp_path, monkeypatch):
        """When LEARNINGS.md doesn't exist, returns empty list."""
        monkeypatch.setattr(apl, "get_learnings_path", lambda: tmp_path / "missing.md")
        result = apl.run_auto_promote()
        assert result == []

    @pytest.mark.unit
    def test_returns_empty_when_no_items(self, tmp_path, monkeypatch):
        """When LEARNINGS.md has no promotable items, returns empty list."""
        learnings_path = tmp_path / "LEARNINGS.md"
        learnings_path.write_text("# Empty\n**Skills Analyzed**: 0\n")
        monkeypatch.setattr(apl, "get_learnings_path", lambda: learnings_path)
        result = apl.run_auto_promote()
        assert result == []

    @pytest.mark.unit
    def test_returns_empty_when_repo_undetectable(self, tmp_path, monkeypatch):
        """When detect_target_repo fails, returns empty list."""
        learnings_path = tmp_path / "LEARNINGS.md"
        learnings_path.write_text(SAMPLE_LEARNINGS)
        monkeypatch.setattr(apl, "get_learnings_path", lambda: learnings_path)
        with patch.object(apl, "detect_target_repo", return_value=None):
            result = apl.run_auto_promote()
        assert result == []

    @pytest.mark.unit
    def test_skips_already_promoted_items(self, tmp_path, monkeypatch):
        """Items already in the promoted record are skipped."""
        learnings_path = tmp_path / "LEARNINGS.md"
        learnings_path.write_text(SAMPLE_LEARNINGS)
        monkeypatch.setattr(apl, "get_learnings_path", lambda: learnings_path)

        # Pre-populate record with all possible keys
        items = apl.parse_improvement_items(SAMPLE_LEARNINGS)
        all_keys = {f"{i['skill']}:{i.get('type', 'unknown')}" for i in items}
        pre_record = apl.PromotedIssueRecord(
            promoted=dict.fromkeys(all_keys, "https://existing")
        )

        record_path = tmp_path / "promoted.json"
        pre_record.save(record_path)

        with (
            patch.object(apl, "detect_target_repo", return_value=("o", "r")),
            patch.object(apl, "PromotedIssueRecord") as mock_cls,
        ):
            mock_cls.load.return_value = pre_record
            result = apl.run_auto_promote()

        assert result == []

    @pytest.mark.unit
    def test_promotes_high_priority_to_issue(self, tmp_path, monkeypatch):
        """High-priority items are promoted to GitHub issues."""
        learnings_path = tmp_path / "LEARNINGS.md"
        learnings_path.write_text(SAMPLE_LEARNINGS)
        monkeypatch.setattr(apl, "get_learnings_path", lambda: learnings_path)

        record = apl.PromotedIssueRecord()
        issue_url = "https://github.com/issues/42"

        with (
            patch.object(apl, "detect_target_repo", return_value=("o", "r")),
            patch.object(apl, "PromotedIssueRecord") as mock_cls,
            patch.object(apl, "has_existing_issue", return_value=False),
            patch.object(apl, "calculate_priority", return_value=10.0),
            patch.object(apl, "promote_to_issue", return_value=issue_url),
            patch.object(apl, "post_to_discussion", return_value=None),
        ):
            mock_cls.load.return_value = record
            result = apl.run_auto_promote()

        assert issue_url in result

    @pytest.mark.unit
    def test_skips_items_with_existing_github_issues(self, tmp_path, monkeypatch):
        """Items with existing GitHub issues are recorded as duplicate-skipped."""
        learnings_path = tmp_path / "LEARNINGS.md"
        learnings_path.write_text(SAMPLE_LEARNINGS)
        monkeypatch.setattr(apl, "get_learnings_path", lambda: learnings_path)

        record = apl.PromotedIssueRecord()

        with (
            patch.object(apl, "detect_target_repo", return_value=("o", "r")),
            patch.object(apl, "PromotedIssueRecord") as mock_cls,
            patch.object(apl, "has_existing_issue", return_value=True),
        ):
            mock_cls.load.return_value = record
            result = apl.run_auto_promote()

        assert result == []


# ---------------------------------------------------------------------------
# main() entry point
# ---------------------------------------------------------------------------


class TestMain:
    """main() is a graceful CLI entry point."""

    @pytest.mark.unit
    def test_main_prints_urls_when_promoted(self, capsys):
        """When items are promoted, URLs are printed."""
        with patch.object(
            apl, "run_auto_promote", return_value=["https://github.com/i/1"]
        ):
            apl.main()

        captured = capsys.readouterr().out
        assert "https://github.com/i/1" in captured

    @pytest.mark.unit
    def test_main_prints_no_items_when_empty(self, capsys):
        """When no items promoted, appropriate message printed."""
        with patch.object(apl, "run_auto_promote", return_value=[]):
            apl.main()

        captured = capsys.readouterr().out
        assert "No items promoted" in captured

    @pytest.mark.unit
    def test_main_exits_0_on_exception(self):
        """Exceptions are caught and process exits 0."""
        with patch.object(apl, "run_auto_promote", side_effect=RuntimeError("boom")):
            with pytest.raises(SystemExit) as exc_info:
                apl.main()

        assert exc_info.value.code == 0
