"""Tests for vow_no_ai_attribution hook.

Feature: Block AI attribution strings in git commit messages.

As a Night Market vow enforcement system
I want to detect and block AI attribution strings in commits
So that the codebase history does not contain AI attribution
that violates the no-AI-attribution vow.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from io import StringIO
from pathlib import Path
from unittest.mock import patch

import pytest


@pytest.fixture
def hook_module():
    """Import vow_no_ai_attribution via importlib (hook is a standalone script)."""
    hooks_path = Path(__file__).resolve().parents[3] / "hooks"
    module_path = hooks_path / "vow_no_ai_attribution.py"
    spec = importlib.util.spec_from_file_location("vow_no_ai_attribution", module_path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["vow_no_ai_attribution"] = mod
    spec.loader.exec_module(mod)
    return mod


def _make_input(tool_name="Bash", command="git commit -m 'clean message'"):
    return json.dumps({"tool_name": tool_name, "tool_input": {"command": command}})


class TestIsGitCommit:
    """Feature: Identify git commit commands.

    As the hook
    I want to skip non-commit Bash commands
    So that I only inspect commit operations.
    """

    @pytest.mark.unit
    @pytest.mark.parametrize(
        "command,expected",
        [
            ("git commit -m 'msg'", True),
            ("git   commit --amend", True),
            ("git status", False),
            ("git push", False),
            ("echo 'git commit'", False),
            ("git log", False),
        ],
        ids=[
            "plain-commit",
            "commit-amend",
            "git-status",
            "git-push",
            "echo-with-commit",
            "git-log",
        ],
    )
    def test_is_git_commit_detection(self, hook_module, command, expected):
        """
        Scenario: Correctly identify git commit invocations
        Given a Bash command string
        When _is_git_commit is called
        Then it returns True only for git commit commands
        """
        assert hook_module._is_git_commit(command) == expected


class TestHasAiAttribution:
    """Feature: Detect AI attribution strings.

    As the hook
    I want to scan commit command strings for AI attribution patterns
    So that violations are caught before the commit executes.
    """

    @pytest.mark.unit
    @pytest.mark.parametrize(
        "command",
        [
            "git commit -m 'fix: thing\n\nCo-authored-by: Claude'",
            "git commit -m 'feat: stuff\n\nGenerated by Claude'",
            "git commit -m 'AI-assisted refactor'",
            "git commit -m 'bot \U0001f916 commit'",
            "git commit -m 'see claude.ai for details'",
            "git commit -m 'approved by Anthropic'",
        ],
        ids=[
            "co-authored-by-claude",
            "generated-by-claude",
            "ai-assisted",
            "robot-emoji",
            "claude-ai-url",
            "anthropic",
        ],
    )
    def test_ai_attribution_detected(self, hook_module, command):
        """
        Scenario: Detect known AI attribution strings
        Given a commit command containing an AI attribution string
        When _has_ai_attribution is called
        Then it returns True
        """
        assert hook_module._has_ai_attribution(command) is True

    @pytest.mark.unit
    @pytest.mark.parametrize(
        "command",
        [
            "git commit -m 'fix: correct off-by-one error'",
            "git commit -m 'feat: add user authentication'",
            "git commit -m 'chore: update dependencies'",
            "git commit -m 'chore: add anthropic>=0.40 to deps'",
            "git commit -m 'chore: update anthropic-sdk to 1.2.0'",
            "git commit -m 'feat: wire anthropic client into batch runner'",
        ],
        ids=[
            "bugfix",
            "feature",
            "chore",
            "anthropic-dep-bump",
            "anthropic-sdk-bump",
            "anthropic-package-reference",
        ],
    )
    def test_clean_message_not_flagged(self, hook_module, command):
        """
        Scenario: Allow clean commit messages (including anthropic package refs)
        Given a commit command without AI attribution
        When _has_ai_attribution is called
        Then it returns False
        """
        assert hook_module._has_ai_attribution(command) is False


class TestShadowMode:
    """Feature: Shadow mode controls warn vs block decision.

    As a deployment operator
    I want shadow mode on by default
    So that the hook warns before enforcing fully.
    """

    @pytest.mark.unit
    def test_shadow_mode_on_by_default(self, hook_module):
        """
        Scenario: Shadow mode active when VOW_SHADOW_MODE unset
        Given VOW_SHADOW_MODE is not set
        When _shadow_mode is called
        Then it returns True
        """
        with patch.dict("os.environ", {}, clear=False):
            env = {"VOW_SHADOW_MODE": "1"}
            with patch.dict("os.environ", env):
                assert hook_module._shadow_mode() is True

    @pytest.mark.unit
    def test_shadow_mode_disabled_by_zero(self, hook_module):
        """
        Scenario: Shadow mode disabled when VOW_SHADOW_MODE=0
        Given VOW_SHADOW_MODE=0
        When _shadow_mode is called
        Then it returns False
        """
        with patch.dict("os.environ", {"VOW_SHADOW_MODE": "0"}):
            assert hook_module._shadow_mode() is False

    @pytest.mark.unit
    @pytest.mark.parametrize("val", ["false", "no"])
    def test_shadow_mode_disabled_by_falsy_strings(self, hook_module, val):
        """
        Scenario: Shadow mode disabled by falsy string values
        Given VOW_SHADOW_MODE set to a falsy string
        When _shadow_mode is called
        Then it returns False
        """
        with patch.dict("os.environ", {"VOW_SHADOW_MODE": val}):
            assert hook_module._shadow_mode() is False


class TestMainHook:
    """Feature: Hook main() integrates detection and decision output.

    As the Claude Code hook runner
    I want the hook to emit correct JSON decisions
    So that violations are handled appropriately.
    """

    @pytest.mark.unit
    def test_warn_in_shadow_mode_on_violation(self, hook_module, capsys):
        """
        Scenario: Warn (not block) when shadow mode is on and violation found
        Given a git commit with AI attribution
        And VOW_SHADOW_MODE=1 (default)
        When main() runs
        Then output JSON has decision=warn
        """
        stdin_data = _make_input(
            command="git commit -m 'fix\n\nCo-authored-by: Claude'"
        )
        with patch.dict("os.environ", {"VOW_SHADOW_MODE": "1"}):
            with patch("sys.stdin", StringIO(stdin_data)):
                with pytest.raises(SystemExit) as exc:
                    hook_module.main()
        assert exc.value.code == 0
        captured = capsys.readouterr()
        output = json.loads(captured.out)
        hook_out = output["hookSpecificOutput"]
        assert hook_out["permissionDecision"] == "warn"
        assert "Vow violation" in hook_out["permissionDecisionReason"]

    @pytest.mark.unit
    def test_block_when_shadow_mode_off_and_violation(self, hook_module, capsys):
        """
        Scenario: Block when shadow mode is off and violation found
        Given a git commit with AI attribution
        And VOW_SHADOW_MODE=0
        When main() runs
        Then output JSON has decision=block
        """
        stdin_data = _make_input(command="git commit -m 'fix\n\nGenerated by Claude'")
        with patch.dict("os.environ", {"VOW_SHADOW_MODE": "0"}):
            with patch("sys.stdin", StringIO(stdin_data)):
                with pytest.raises(SystemExit) as exc:
                    hook_module.main()
        assert exc.value.code == 0
        captured = capsys.readouterr()
        output = json.loads(captured.out)
        assert output["hookSpecificOutput"]["permissionDecision"] == "block"

    @pytest.mark.unit
    def test_no_output_on_clean_commit(self, hook_module, capsys):
        """
        Scenario: Allow clean commit without emitting decision JSON
        Given a git commit with no AI attribution
        When main() runs
        Then no JSON is printed to stdout
        """
        stdin_data = _make_input(command="git commit -m 'fix: clean message'")
        with patch.dict("os.environ", {"VOW_SHADOW_MODE": "1"}):
            with patch("sys.stdin", StringIO(stdin_data)):
                with pytest.raises(SystemExit) as exc:
                    hook_module.main()
        assert exc.value.code == 0
        captured = capsys.readouterr()
        assert captured.out.strip() == ""

    @pytest.mark.unit
    def test_non_bash_tool_ignored(self, hook_module, capsys):
        """
        Scenario: Non-Bash tool calls pass through silently
        Given a Write tool call (not Bash)
        When main() runs
        Then no output is produced
        """
        stdin_data = json.dumps(
            {
                "tool_name": "Write",
                "tool_input": {"file_path": "/tmp/x.py", "content": ""},
            }
        )
        with patch("sys.stdin", StringIO(stdin_data)):
            with pytest.raises(SystemExit) as exc:
                hook_module.main()
        assert exc.value.code == 0
        captured = capsys.readouterr()
        assert captured.out.strip() == ""

    @pytest.mark.unit
    def test_non_commit_bash_ignored(self, hook_module, capsys):
        """
        Scenario: Non-commit Bash commands pass through silently
        Given a Bash call running git status
        When main() runs
        Then no output is produced
        """
        stdin_data = _make_input(command="git status")
        with patch("sys.stdin", StringIO(stdin_data)):
            with pytest.raises(SystemExit) as exc:
                hook_module.main()
        assert exc.value.code == 0
        captured = capsys.readouterr()
        assert captured.out.strip() == ""

    @pytest.mark.unit
    def test_malformed_stdin_exits_cleanly(self, hook_module, capsys):
        """
        Scenario: Malformed stdin does not crash the hook
        Given non-JSON input on stdin
        When main() runs
        Then it exits 0 without output (fail-safe)
        """
        with patch("sys.stdin", StringIO("not valid json")):
            with pytest.raises(SystemExit) as exc:
                hook_module.main()
        assert exc.value.code == 0
        captured = capsys.readouterr()
        assert captured.out.strip() == ""
