"""GitHub issue creation for human-gated rollback review.

When the re-evaluation window (execution-count-based) detects regression, this module
generates a GitHub issue with all context needed for a human
to decide whether to rollback.

Part of the self-adapting system. See:
docs/plans/2026-02-15-self-adapting-systems-design.md
"""

from __future__ import annotations

import json
import re
import subprocess  # nosec: B404
import sys
from pathlib import Path


class RollbackReviewer:
    """Creates GitHub issues for regression review."""

    def generate_issue_title(self, skill_name: str) -> str:
        """Generate issue title for a skill regression."""
        return f"Skill regression detected: {skill_name}"

    def generate_issue_body(
        self,
        skill_name: str,
        baseline_gap: float,
        current_gap: float,
        improvement_diff: str,
        rollback_command: str,
    ) -> str:
        """Generate GitHub issue body with full regression context."""
        return f"""## Skill Regression Report

**Skill**: `{skill_name}`
**Label**: `skill-regression`

### Metrics

| Metric | Before (baseline) | After (current) |
|---|---|---|
| Stability Gap | {baseline_gap:.3f} | {current_gap:.3f} |

### What Changed

```
{improvement_diff}
```

### Rollback Command

```bash
{rollback_command}
```

### Decision Options

1. **Rollback**: Run the command above to revert to the previous version
2. **Keep**: Close this issue if the regression is acceptable or transient
3. **Investigate**: Request further analysis before deciding

### Context

This issue was auto-generated by the homeostatic monitoring system.
The skill was improved automatically but showed regression during the
10-execution evaluation window. Human review is required before rollback.
"""

    def generate_rollback_command(self, commit_hash: str) -> str:
        """Generate a git revert command for a commit.

        Raises ValueError if commit_hash contains invalid characters
        to prevent command injection.
        """
        if not re.match(r"^[a-f0-9]+$", commit_hash):
            raise ValueError(
                f"Invalid commit hash {commit_hash!r}: "
                "must contain only lowercase hex characters (a-f, 0-9)."
            )
        return f"git revert {commit_hash} --no-edit"

    def create_github_issue(
        self,
        skill_name: str,
        baseline_gap: float,
        current_gap: float,
        improvement_diff: str,
        rollback_command: str,
    ) -> str | None:
        """Create a GitHub issue via the shared deferred_capture script.

        Returns the issue URL if successful, None otherwise.
        """
        script = Path(__file__).resolve().parents[2] / "scripts" / "deferred_capture.py"
        context = (
            f"Skill regression detected for {skill_name}.\n"
            f"Baseline stability gap: {baseline_gap:.3f}\n"
            f"Current stability gap: {current_gap:.3f}\n"
            f"Improvement diff: {improvement_diff}\n"
            f"Rollback command: {rollback_command}"
        )
        try:
            result = subprocess.run(  # nosec: B603
                [
                    sys.executable,
                    str(script),
                    "--title",
                    f"Skill regression: {skill_name}",
                    "--source",
                    "regression",
                    "--context",
                    context,
                    "--captured-by",
                    "explicit",
                ],
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )
            if result.returncode == 0:
                try:
                    data = json.loads(result.stdout)
                    url = data.get("issue_url")
                except json.JSONDecodeError:
                    url = None
                return str(url) if url is not None else None
            sys.stderr.write(
                f"rollback_reviewer: deferred_capture failed: {result.stderr.strip()}\n"
            )
            return None
        except (
            FileNotFoundError,
            subprocess.TimeoutExpired,
            json.JSONDecodeError,
        ) as e:
            sys.stderr.write(f"rollback_reviewer: {e}\n")
            return None
