#!/usr/bin/env python3
"""Vow: No AI attribution in commits (Hard layer).

PreToolUse hook that blocks (or warns in shadow mode) when a
`git commit` command contains AI attribution strings such as
"Co-authored-by: Claude", "Generated by Claude", "AI-assisted",
or the robot emoji.

Shadow mode is ON by default (warn only).  Set VOW_SHADOW_MODE=0
to switch to full blocking.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# D-06: shadow_mode + is_git_commit live in shared/vow_utils.
sys.path.insert(0, str(Path(__file__).parent))
from shared.vow_utils import (  # noqa: E402 - hook script must inject sys.path before importing sibling shared/ module
    is_git_commit,
    shadow_mode_active,
)

# Known AI coding tools. Extending coverage (Codeium, Cody, Tabnine,
# Windsurf, Devin, Sweep, etc.) is a one-line change in these two lists;
# the regexes below consume them at module load.
_AI_TOOL_NAMES = ["Claude", "Anthropic", "Cursor", "Copilot"]
_AI_TOOL_DOMAINS = [r"claude\.ai", r"anthropic\.com", r"cursor\.(?:sh|com)"]

_TOOL_NAME_GROUP = "|".join(_AI_TOOL_NAMES)
_TOOL_DOMAIN_GROUP = "|".join(_AI_TOOL_DOMAINS)

# Strong attribution verbs: trailer keywords and canonical prose that
# always signal credit assignment. A tool name on the same line as one
# of these is unambiguous AI attribution.
_STRONG_ATTRIBUTION_PREFIX = (
    r"Co-authored(?:-by)?"
    r"|Generated\s+by"
    r"|Authored\s+by"
    r"|Approved\s+by"
    r"|Signed-off-by"
    r"|Composed\s+by"
    r"|Written\s+by"
    r"|Created\s+by"
    r"|Reviewed\s+by"
    r"|Verified\s+by"
)

# Patterns that indicate AI attribution in a commit message.
#
# Every pattern requires an ATTRIBUTION CONTEXT -- a trailer keyword, an
# attribution verb, or an explicit marker. Bare tool names and URLs
# ("chore: bump anthropic>=0.40", "docs: link to anthropic.com", "fix:
# cursor positioning") do NOT match, which is the false-positive class
# documented in PR #417 review finding B1.
_AI_ATTRIBUTION_PATTERNS = [
    # Strong verb followed by a known tool name on the same line.
    # Handles "Co-authored-by: Claude ...", "Generated by Cursor",
    # "Reviewed by Copilot", and similar across all covered tools.
    rf"(?:{_STRONG_ATTRIBUTION_PREFIX}):?[^\n]*?\b(?:{_TOOL_NAME_GROUP})\b",
    # Weak verb (by/from/via) followed by a known tool domain on the
    # same line. Domains are attribution-unambiguous even with weak
    # verbs: "by claude.ai", "from anthropic.com".
    rf"\b(?:by|from|via)\b[^\n]*?\b(?:{_TOOL_DOMAIN_GROUP})\b",
    # GitHub Copilot bot trailer -- the "[bot]" suffix is explicit.
    r"\bgithub-copilot\[bot\]",
    # Generic attribution markers.
    r"\bAI-assisted\b",
    r"\U0001F916",  # robot emoji
]

_COMPILED = [re.compile(p, re.IGNORECASE) for p in _AI_ATTRIBUTION_PATTERNS]


def _is_git_commit(command: str) -> bool:
    """Return True if the Bash command is a git commit invocation."""
    return is_git_commit(command)


def _has_ai_attribution(command: str) -> bool:
    """Return True if *command* contains an AI attribution string."""
    for pattern in _COMPILED:
        if pattern.search(command):
            return True
    return False


def _shadow_mode() -> bool:
    """Return True when shadow (warn-only) mode is active."""
    return shadow_mode_active()


def main() -> None:
    """Entry point for the PreToolUse hook."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw)
    except (json.JSONDecodeError, OSError):
        sys.exit(0)

    try:
        tool_name = data.get("tool_name", "")
        if tool_name != "Bash":
            sys.exit(0)

        command = data.get("tool_input", {}).get("command", "")
        if not _is_git_commit(command):
            sys.exit(0)

        if not _has_ai_attribution(command):
            sys.exit(0)

        shadow = _shadow_mode()
        decision = "warn" if shadow else "block"
        reason = (
            "Vow violation: AI attribution detected in commit message. "
            "Night Market vow prohibits AI attribution strings in commits "
            "(Hard vow). "
            + (
                "Shadow mode active -- this will block once VOW_SHADOW_MODE=0."
                if shadow
                else ""
            )
        )

        output = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": decision,
                "permissionDecisionReason": reason,
            }
        }
        print(json.dumps(output))
        print(
            f"[vow-no-ai-attribution] {decision.upper()}: AI attribution in commit",
            file=sys.stderr,
        )
        sys.exit(0)

    except Exception:  # hook must not crash the agent under any circumstance
        sys.exit(0)


if __name__ == "__main__":
    main()
