#!/usr/bin/env python3
"""Vow: No AI attribution in commits (Hard layer).

PreToolUse hook that blocks (or warns in shadow mode) when a
`git commit` command contains AI attribution strings such as
"Co-authored-by: Claude", "Generated by Claude", "AI-assisted",
or the robot emoji.

Shadow mode is ON by default (warn only).  Set VOW_SHADOW_MODE=0
to switch to full blocking.
"""

from __future__ import annotations

import json
import os
import re
import sys

# Patterns that indicate AI attribution in a commit message.
_AI_ATTRIBUTION_PATTERNS = [
    r"Co-authored-by:\s*Claude",
    r"Generated by Claude",
    r"AI-assisted",
    r"\U0001F916",
    r"claude\.ai",
    r"anthropic",
]

_COMPILED = [re.compile(p, re.IGNORECASE) for p in _AI_ATTRIBUTION_PATTERNS]


def _is_git_commit(command: str) -> bool:
    """Return True if the Bash command is a git commit invocation."""
    stripped = command.strip()
    return bool(re.match(r"git\s+commit\b", stripped))


def _has_ai_attribution(command: str) -> bool:
    """Return True if *command* contains an AI attribution string."""
    for pattern in _COMPILED:
        if pattern.search(command):
            return True
    return False


def _shadow_mode() -> bool:
    """Return True when shadow (warn-only) mode is active.

    Shadow mode is the default.  Set VOW_SHADOW_MODE=0 to enable blocking.
    """
    val = os.environ.get("VOW_SHADOW_MODE", "1")
    return val.strip() not in ("0", "false", "no")


def main() -> None:
    """Entry point for the PreToolUse hook."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw)
    except (json.JSONDecodeError, OSError):
        sys.exit(0)

    try:
        tool_name = data.get("tool_name", "")
        if tool_name != "Bash":
            sys.exit(0)

        command = data.get("tool_input", {}).get("command", "")
        if not _is_git_commit(command):
            sys.exit(0)

        if not _has_ai_attribution(command):
            sys.exit(0)

        shadow = _shadow_mode()
        decision = "warn" if shadow else "block"
        reason = (
            "Vow violation: AI attribution detected in commit message. "
            "Night Market vow prohibits AI attribution strings in commits "
            "(Hard vow). "
            + (
                "Shadow mode active -- this will block once VOW_SHADOW_MODE=0."
                if shadow
                else ""
            )
        )

        output = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": decision,
                "permissionDecisionReason": reason,
            }
        }
        print(json.dumps(output))
        print(
            f"[vow-no-ai-attribution] {decision.upper()}: AI attribution in commit",
            file=sys.stderr,
        )
        sys.exit(0)

    except Exception:  # hook must not crash the agent under any circumstance
        sys.exit(0)


if __name__ == "__main__":
    main()
