"""Shared thresholds for test quality analysis."""

from __future__ import annotations

MIN_COVERAGE_RATIO = 0.8
ACCEPTABLE_COVERAGE_RATIO = 0.5
MIN_ASSERTION_DENSITY = 0.5
MIN_MUTATION_SCORE = 0.7
MIN_COVERAGE_PERCENT = 80
MIN_MOCK_RATIO = 0.2
MAX_AVG_TEST_DURATION = 2.0
VERY_SLOW_TEST_THRESHOLD = 10.0
SLOW_TEST_THRESHOLD = 5.0
MIN_COMPLEX_ASSERTIONS = 3
MIN_EDGE_CASES = 5
MAX_ANTI_PATTERNS = 5
MAX_UNSAFE_BLOCKS = 20
