"""Shared test constants for conserve plugin tests.

This module provides magic number constants shared across all conserve
plugin tests to avoid duplication and validate consistency. Import these
constants instead of defining them locally in test files.

Categories:
- Basic Numbers: Simple numeric constants (TWO, THREE, FIVE, etc.)
- Decimals: Decimal/float constants (ZERO_POINT_FIVE, etc.)
- Hundreds/Thousands: Larger numeric constants
- Thresholds: Test threshold values
"""

# Basic Numbers (commonly used across tests)
TWO = 2
THREE = 3
FOUR = 4
FIVE = 5
SIX = 6
EIGHT = 8
TEN = 10
TWELVE = 12
FOURTEEN = 14
FIFTEEN = 15
EIGHTEEN = 18
TWENTY = 20
TWENTY_FIVE = 25
THIRTY = 30
THIRTY_TWO = 32
THIRTY_FIVE = 35
FIFTY = 50
SIXTY = 60
SEVENTY = 70
SEVENTY_FIVE = 75
EIGHTY = 80
EIGHTY_FIVE = 85
NINETY = 90
HUNDRED = 100

# Decimal/Float Constants
ZERO_POINT_ZERO_TWO = 0.02
ZERO_POINT_TWENTY_FOUR = 0.24
ZERO_POINT_THREE = 0.3
ZERO_POINT_FIVE = 0.5
ZERO_POINT_SEVEN = 0.7
ZERO_POINT_EIGHT = 0.8
ZERO_POINT_EIGHTY_FIVE = 0.85
ZERO_POINT_NINE = 0.9
TWO_POINT_ZERO = 2.0
TEN_POINT_ZERO = 10.0
TWENTY_POINT_ZERO = 20.0
THIRTY_POINT_ZERO = 30.0
THIRTY_FIVE_POINT_ZERO = 35.0
FORTY_TWO_POINT_FIVE = 42.5
FIFTY_POINT_ZERO = 50.0
SIXTY_FIVE_POINT_ZERO = 65.0
NINETY_POINT_ZERO = 90.0
ONE_FIFTY_POINT_ZERO = 150.0

# Hundreds
TWO_HUNDRED = 200
TWO_HUNDRED_SEVENTY = 270
THREE_HUNDRED = 300
SEVEN_HUNDRED_FIFTY_FIVE = 755
EIGHT_HUNDRED = 800

# Thousands
ONE_THOUSAND_TWENTY_FIVE = 1025
TWELVE_HUNDRED = 1200
FIFTEEN_HUNDRED = 1500
THOUSAND = 1000
TWO_THOUSAND = 2000
THREE_THOUSAND = 3000
FOUR_THOUSAND_NINETY_SIX = 4096
FIVE_THOUSAND = 5000
EIGHT_THOUSAND_ONE_HUNDRED_NINETY_TWO = 8192
EIGHT_THOUSAND_TWO_HUNDRED = 8200
TWELVE_THOUSAND = 12000
FIFTEEN_THOUSAND = 15000
TWENTY_THOUSAND = 20000
TWENTY_FOUR_THOUSAND = 24000
EIGHTY_FIVE_THOUSAND = 85000
HUNDRED_THOUSAND = 100000
HUNDRED_EIGHT_THOUSAND = 108000
TWO_HUNDRED_THOUSAND = 200000

# Test Thresholds and Limits
CPU_USAGE_THRESHOLD = 80
TOKEN_USAGE_THRESHOLD = 10000
MECW_THRESHOLD = 0.5  # 50% rule
LOW_UTILIZATION_THRESHOLD = 0.3
OPTIMAL_UTILIZATION_THRESHOLD = 0.5
HIGH_UTILIZATION_THRESHOLD = 0.7
