"""Shared constants for makefile analysis."""

from __future__ import annotations

MIN_TARGETS_FOR_PARALLEL = 5
MIN_RECIPE_LINES_FOR_LARGE_TARGET = 3
MIN_CP_OPERATIONS_FOR_WARNING = 3

_SCORE_PHONY = 1.5
_SCORE_IMMEDIATE_ASSIGN = 1.0
_SCORE_INCLUDE = 1.0
_SCORE_SHELL_OVERRIDE = 0.5
_SCORE_PATTERN_RULES = 1.0
_SCORE_ORDER_PREREQS = 1.0
_SCORE_PRECIOUS = 0.5
_SCORE_CROSS_COMPILE = 1.5
_SCORE_MK_INCLUDE = 1.0
